**Jogos Olímpicos de Verão de 1960 - Roma**

In [63]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_1960 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_1960"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_1960, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_1960 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1960 = df_1960.iloc[:, :6]
df_1960.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1960 = df_1960.fillna(0)
df_1960 = df_1960[df_1960['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_1960[colunas_num] = df_1960[colunas_num].astype(int)

df_1960['País'] = df_1960['País'].str.strip()

df_1960

    Ordem                                 País  Ouro  Prata  Bronze  Total
0       1                  URS União Soviética    43     29      31    103
1       2                   USA Estados Unidos    34     21      16     71
2       3                           ITA Itália    13     10      13     36
3       4               EUA Equipe Alemã Unida    12     19      11     42
4       5                        AUS Austrália     8      8       6     22
5       6                          TUR Turquia     7      2       0      9
6       7                          HUN Hungria     6      8       7     21
7       8                            JPN Japão     4      7       7     18
8       9                          POL Polônia     4      6      11     21
9      10                   TCH Checoslováquia     3      2       3      8
10     11                          ROU Romênia     3      1       6     10
11     12                     GBR Grã-Bretanha     2      6      12     20
12     13                        DEN Dinamarca     2      3       1      6
13     14                    NZL Nova Zelândia     2      0       1      3
14     15                         BUL Bulgária     1      3       3      7
15     16                           SWE Suécia     1      2       3      6
16     17                        FIN Finlândia     1      1       3      5
17     18                          AUT Áustria     1      1       0      2
18     18                       YUG Iugoslávia     1      1       0      2
19     20                        PAK Paquistão     1      0       1      2
20     21                          ETH Etiópia     1      0       0      1
21     21                           GRE Grécia     1      0       0      1
22     21                          NOR Noruega     1      0       0      1
23     24                            SUI Suíça     0      3       3      6
24     25                           FRA França     0      2       3      5
25     26                          BEL Bélgica     0      2       2      4
26     27                              IRI Irã     0      1       3      4
27     28                    NED Países Baixos     0      1       2      3
28     28                    RSA África do Sul     0      1       2      3
29     30                        ARG Argentina     0      1       1      2
30     30                            EGY Egito     0      1       1      2
31     32                           CAN Canadá     0      1       0      1
32     32               ROC República da China     0      1       0      1
33     32                             GHA Gana     0      1       0      1
34     32                            IND Índia     0      1       0      1
35     32                         MAR Marrocos     0      1       0      1
36     32                         POR Portugal     0      1       0      1
37     32                        SIN Singapura     0      1       0      1
38     39                           BRA Brasil     0      0       2      2
39     39  BWI Federação das Índias Ocidentais     0      0       2      2
40     41                           IRQ Iraque     0      0       1      1
41     41                           MEX México     0      0       1      1
42     41                          ESP Espanha     0      0       1      1
43     41                        VEN Venezuela     0      0       1      1

In [61]:
df_1960.to_csv("medalhas_roma_1960_oficial.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Olímpicos de Verão de 1964 - Japão**

In [60]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_1964 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_1964"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_1964, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_1964 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1964 = df_1964.iloc[:, :6]
df_1964.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1964 = df_1964.fillna(0)
df_1964 = df_1964[df_1964['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_1964[colunas_num] = df_1964[colunas_num].astype(int)

df_1964['País'] = df_1964['País'].str.strip()

df_1964.to_csv("medalhas_toquio_1964.csv", index=False, sep=',', encoding='utf-8-sig')

df_1964

    Ordem                    País  Ouro  Prata  Bronze  Total
0       1      USA Estados Unidos    36     26      28     90
1       2     URS União Soviética    30     31      35     96
2       3               JPN Japão    16      5       8     29
3       4  EUA Equipe Alemã Unida    10     22      18     50
4       5              ITA Itália    10     10       7     27
5       6             HUN Hungria    10      7       5     22
6       7             POL Polônia     7      6      10     23
7       8           AUS Austrália     6      2      10     18
8       9      TCH Checoslováquia     5      6       3     14
9      10        GBR Grã-Bretanha     4     12       2     18
10     11            BUL Bulgária     3      5       2     10
11     12           FIN Finlândia     3      0       2      5
12     12       NZL Nova Zelândia     3      0       2      5
13     14             ROU Romênia     2      4       6     12
14     15       NED Países Baixos     2      4       4     10
15     16             TUR Turquia     2      3       1      6
16     17              SWE Suécia     2      2       4      8
17     18           DEN Dinamarca     2      1       3      6
18     19          YUG Iugoslávia     2      1       2      5
19     20             BEL Bélgica     2      0       1      3
20     21              FRA França     1      8       6     15
21     22              CAN Canadá     1      2       1      4
22     22               SUI Suíça     1      2       1      4
23     24             BAH Bahamas     1      0       0      1
24     24             ETH Etiópia     1      0       0      1
25     24               IND Índia     1      0       0      1
26     27       KOR Coreia do Sul     0      2       1      3
27     28   TRI Trinidad e Tobago     0      1       2      3
28     29             TUN Tunísia     0      1       1      2
29     30           ARG Argentina     0      1       0      1
30     30                CUB Cuba     0      1       0      1
31     30           PAK Paquistão     0      1       0      1
32     30           PHI Filipinas     0      1       0      1
33     34                 IRI Irã     0      0       2      2
34     35              BRA Brasil     0      0       1      1
35     35                GHA Gana     0      0       1      1
36     35             IRL Irlanda     0      0       1      1
37     35              KEN Quênia     0      0       1      1
38     35              MEX México     0      0       1      1
39     35             NGR Nigéria     0      0       1      1
40     35             URU Uruguai     0      0       1      1

In [59]:
df_1964.to_csv("medalhas_toquio_1964.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Olímpicos de Verão de 1968 - Mexico**

In [58]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_1968 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_1968"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_1968, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_1968 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1968 = df_1968.iloc[:, :6]
df_1968.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1968 = df_1968.fillna(0)
df_1968 = df_1968[df_1968['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_1968[colunas_num] = df_1968[colunas_num].astype(int)

df_1968['País'] = df_1968['País'].str.strip()

df_1968.to_csv("medalhas_mexico_1968.csv", index=False, sep=',', encoding='utf-8-sig')

df_1968

    Ordem                    País  Ouro  Prata  Bronze  Total
0       1      USA Estados Unidos    45     28      34    107
1       2     URS União Soviética    29     32      30     91
2       3               JPN Japão    11      7       7     25
3       4             HUN Hungria    10     10      12     32
4       5   GDR Alemanha Oriental     9      9       7     25
5       6              FRA França     7      3       5     15
6       7      TCH Checoslováquia     7      2       4     13
7       8  FRG Alemanha Ocidental     5     11      10     26
8       9           AUS Austrália     5      7       5     17
9      10        GBR Grã-Bretanha     5      5       3     13
10     11             POL Polônia     5      2      11     18
11     12             ROU Romênia     4      6       5     15
12     13              ITA Itália     3      4       9     16
13     14              KEN Quênia     3      4       2      9
14     15              MEX México     3      3       3      9
15     16          YUG Iugoslávia     3      3       2      8
16     17       NED Países Baixos     3      3       1      7
17     18            BUL Bulgária     2      4       3      9
18     19                 IRI Irã     2      1       2      5
19     20              SWE Suécia     2      1       1      4
20     21             TUR Turquia     2      0       0      2
21     22           DEN Dinamarca     1      4       3      8
22     23              CAN Canadá     1      3       1      5
23     24           FIN Finlândia     1      2       1      4
24     25             ETH Etiópia     1      1       0      2
25     25             NOR Noruega     1      1       0      2
26     27       NZL Nova Zelândia     1      0       2      3
27     28             TUN Tunísia     1      0       1      2
28     29           PAK Paquistão     1      0       0      1
29     29           VEN Venezuela     1      0       0      1
30     31                CUB Cuba     0      4       0      4
31     32             AUT Áustria     0      2       2      4
32     33               SUI Suíça     0      1       4      5
33     34            MGL Mongólia     0      1       3      4
34     35              BRA Brasil     0      1       2      3
35     36             BEL Bélgica     0      1       1      2
36     36       KOR Coreia do Sul     0      1       1      2
37     36              UGA Uganda     0      1       1      2
38     39            CMR Camarões     0      1       0      1
39     39             JAM Jamaica     0      1       0      1
40     41           ARG Argentina     0      0       2      2
41     42              GRE Grécia     0      0       1      1
42     42               IND Índia     0      0       1      1
43     42              ROC Taiwan     0      0       1      1

In [57]:
df_1968.to_csv("medalhas_mexico_1968.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Olímpicos de Verão de 1972 - Alemanha**

In [55]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_1972 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_1972"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_1972, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_1972 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1972 = df_1972.iloc[:, :6]
df_1972.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1972 = df_1972.fillna(0)
df_1972 = df_1972[df_1972['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_1972[colunas_num] = df_1972[colunas_num].astype(int)

df_1972['País'] = df_1972['País'].str.strip()

df_1972.to_csv("medalhas_munique_1972.csv", index=False, sep=',', encoding='utf-8-sig')

df_1972

    Ordem                    País  Ouro  Prata  Bronze  Total
0       1     URS União Soviética    50     27      22     99
1       2      USA Estados Unidos    33     31      30     94
2       3   GDR Alemanha Oriental    20     23      23     66
3       4  FRG Alemanha Ocidental    13     11      16     40
4       5               JPN Japão    13      8       8     29
5       6           AUS Austrália     8      7       2     17
6       7             POL Polônia     7      5       9     21
7       8             HUN Hungria     6     13      16     35
8       9            BUL Bulgária     6     10       5     21
9      10              ITA Itália     5      3      10     18
10     11              SWE Suécia     4      6       6     16
11     12        GBR Grã-Bretanha     4      5       9     18
12     13             ROU Romênia     3      6       7     16
13     14                CUB Cuba     3      1       4      8
14     14           FIN Finlândia     3      1       4      8
15     16       NED Países Baixos     3      1       1      5
16     17              FRA França     2      4       7     13
17     18      TCH Checoslováquia     2      4       2      8
18     19              KEN Quênia     2      3       4      9
19     20          YUG Iugoslávia     2      1       2      5
20     21             NOR Noruega     2      1       1      4
21     22     PRK Coreia do Norte     1      1       3      5
22     23       NZL Nova Zelândia     1      1       1      3
23     24              UGA Uganda     1      1       0      2
24     25           DEN Dinamarca     1      0       0      1
25     26               SUI Suíça     0      3       0      3
26     27              CAN Canadá     0      2       3      5
27     28                 IRI Irã     0      2       1      3
28     29             BEL Bélgica     0      2       0      2
29     29              GRE Grécia     0      2       0      2
30     31             AUT Áustria     0      1       2      3
31     31            COL Colômbia     0      1       2      3
32     33           ARG Argentina     0      1       0      1
33     33       KOR Coreia do Sul     0      1       0      1
34     33              LIB Líbano     0      1       0      1
35     33              MEX México     0      1       0      1
36     33            MGL Mongólia     0      1       0      1
37     33           PAK Paquistão     0      1       0      1
38     33             TUN Tunísia     0      1       0      1
39     33             TUR Turquia     0      1       0      1
40     41              BRA Brasil     0      0       2      2
41     41             ETH Etiópia     0      0       2      2
42     43                GHA Gana     0      0       1      1
43     43               IND Índia     0      0       1      1
44     43             JAM Jamaica     0      0       1      1
45     43               NIG Níger     0      0       1      1
46     43             NGR Nigéria     0      0       1      1
47     43             ESP Espanha     0      0       1      1

In [56]:
df_1972.to_csv("medalhas_munique_1972.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Olímpicos de Verão de 1976 - Canadá**

In [54]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_1976 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_1976"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_1976, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_1976 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1976 = df_1976.iloc[:, :6]
df_1976.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1976 = df_1976.fillna(0)
df_1976 = df_1976[df_1976['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_1976[colunas_num] = df_1976[colunas_num].astype(int)

df_1976['País'] = df_1976['País'].str.strip()

df_1976.to_csv("medalhas_montreal_1976.csv", index=False, sep=',', encoding='utf-8-sig')

df_1976

   Ordem                    País  Ouro  Prata  Bronze  Total
0      1     URS União Soviética    49     41      35    125
1      2   GDR Alemanha Oriental    40     25      25     90
2      3      USA Estados Unidos    34     35      25     94
3      4  FRG Alemanha Ocidental    10     12      17     39
4      5               JPN Japão     9      6      10     25
5      6             POL Polônia     7      6      13     26
6      7            BUL Bulgária     6      9       7     22
7      8                CUB Cuba     6      4       3     13
8      9             ROU Romênia     4      9      14     27
9     10             HUN Hungria     4      5      13     22
10    11           FIN Finlândia     4      2       0      6
11    12              SWE Suécia     4      1       0      5
12    13        GBR Grã-Bretanha     3      5       5     13
13    14              ITA Itália     2      7       4     13
14    15              FRA França     2      3       4      9
15    16          YUG Iugoslávia     2      3       3      8
16    17      TCH Checoslováquia     2      2       4      8
17    18       NZL Nova Zelândia     2      1       1      4
18    19       KOR Coreia do Sul     1      1       4      6
19    20               SUI Suíça     1      1       2      4
20    21             JAM Jamaica     1      1       0      2
21    21     PRK Coreia do Norte     1      1       0      2
22    21             NOR Noruega     1      1       0      2
23    24           DEN Dinamarca     1      0       2      3
24    25              MEX México     1      0       1      2
25    26   TRI Trinidad e Tobago     1      0       0      1
26    27              CAN Canadá     0      5       6     11
27    28             BEL Bélgica     0      3       3      6
28    29       NED Países Baixos     0      2       3      5
29    30            POR Portugal     0      2       0      2
30    30             ESP Espanha     0      2       0      2
31    32           AUS Austrália     0      1       4      5
32    33                 IRI Irã     0      1       1      2
33    34            MGL Mongólia     0      1       0      1
34    34           VEN Venezuela     0      1       0      1
35    36              BRA Brasil     0      0       2      2
36    37             AUT Áustria     0      0       1      1
37    37            BER Bermudas     0      0       1      1
38    37           PAK Paquistão     0      0       1      1
39    37          PUR Porto Rico     0      0       1      1
40    37           THA Tailândia     0      0       1      1

In [53]:
df_1976.to_csv("medalhas_montreal_1976.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Olímpicos de Verão de 1980 - Rússia**

o quadro de medalhas é bastante atípico devido ao grande boicote liderado pelos Estados Unidos. Isso resultou em um domínio massivo da União Soviética e da Alemanha Oriental.

In [51]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_1980 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_1980"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_1980, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_1980 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1980 = df_1980.iloc[:, :6]
df_1980.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1980 = df_1980.fillna(0)
df_1980 = df_1980[df_1980['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_1980[colunas_num] = df_1980[colunas_num].astype(int)

df_1980['País'] = df_1980['País'].str.strip()

df_1980.to_csv("medalhas_moscou_1980.csv", index=False, sep=',', encoding='utf-8-sig')

df_1980

    Ordem                   País  Ouro  Prata  Bronze  Total
0       1    URS União Soviética    80     69      46    195
1       2  GDR Alemanha Oriental    47     37      42    126
2       3           BUL Bulgária     8     16      17     41
3       4               CUB Cuba     8      7       5     20
4       5             ITA Itália     8      3       4     15
5       6            HUN Hungria     7     10      15     32
6       7            ROM Romênia     6      6      13     25
7       8             FRA França     6      5       3     14
8       9       GBR Grã-Bretanha     5      7       9     21
9      10            POL Polônia     3     14      15     32
10     11             SWE Suécia     3      3       6     12
11     12          FIN Finlândia     3      1       4      8
12     13     TCH Checoslováquia     2      3       9     14
13     14         YUG Iugoslávia     2      3       4      9
14     15          AUS Austrália     2      2       5      9
15     16          DEN Dinamarca     2      1       2      5
16     17             BRA Brasil     2      0       2      4
17     17            ETH Etiópia     2      0       2      4
18     19              SUI Suíça     2      0       0      2
19     20            ESP Espanha     1      3       2      6
20     21            AUT Áustria     1      2       1      4
21     22             GRE Grécia     1      0       2      4
22     23            BEL Bélgica     1      0       0      1
23     23              IND Índia     1      0       0      1
24     23           ZIM Zimbabwe     1      0       0      1
25     26    PRK Coreia do Norte     0      3       2      5
26     27           MGL Mongólia     0      2       2      4
27     28           TAN Tanzânia     0      2       0      2
28     29             MEX México     0      1       3      4
29     30      NED Países Baixos     0      1       2      3
30     31            IRL Irlanda     0      1       1      2
31     32             UGA Uganda     0      1       0      1
32     32          VEN Venezuela     0      1       0      1
33     34            JAM Jamaica     0      0       3      3
34     35             GUY Guiana     0      0       1      1
35     35             LIB Líbano     0      0       1      1

In [52]:
df_1980.to_csv("medalhas_moscou_1980.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Olímpicos de Verão de 1984 - EUA**

desta vez, a União Soviética e a maioria dos países do bloco oriental boicotaram os jogos. Isso resultou em um domínio recorde dos Estados Unidos.

In [50]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_1984 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_1984"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_1984, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_1984 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1984 = df_1984.iloc[:, :6]
df_1984.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1984 = df_1984.fillna(0)
df_1984 = df_1984[df_1984['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_1984[colunas_num] = df_1984[colunas_num].astype(int)

df_1984.to_csv("medalhas_la_1984.csv", index=False, sep=',', encoding='utf-8-sig')

df_1984

    Ordem                      País  Ouro  Prata  Bronze  Total
0       1        USA Estados Unidos    83     61      30    174
1       2               ROU Romênia    20     16      17     53
2       3    FRG Alemanha Ocidental    17     19      23     59
3       4                 CHN China    15      8       9     32
4       5                ITA Itália    14      6      12     32
5       6                CAN Canadá    10     18      16     44
6       7                 JPN Japão    10      8      14     32
7       8         NZL Nova Zelândia     8      1       2     11
8       9            YUG Iugoslávia     7      4       7     18
9      10         KOR Coreia do Sul     6      6       7     19
10     11          GBR Grã-Bretanha     5     11      21     37
11     12                FRA França     5      7      16     28
12     13         NED Países Baixos     5      2       6     13
13     14             AUS Austrália     4      8      12     24
14     15             FIN Finlândia     4      2       6     12
15     16                SWE Suécia     2     11       6     19
16     17                MEX México     2      3       1      6
17     18              MAR Marrocos     2      0       0      2
18     19                BRA Brasil     1      5       2      8
19     20               ESP Espanha     1      2       2      5
20     21               BEL Bélgica     1      1       2      4
21     22               AUT Áustria     1      1       1      3
22     23                KEN Quênia     1      0       2      3
23     23              POR Portugal     1      0       2      3
24     25             PAK Paquistão     1      0       0      1
25     26                 SUI Suíça     0      4       4      8
26     27             DEN Dinamarca     0      3       3      6
27     28               JAM Jamaica     0      1       2      3
28     28               NOR Noruega     0      1       2      3
29     30                GRE Grécia     0      1       1      2
30     30               NGR Nigéria     0      1       1      2
31     30            PUR Porto Rico     0      1       1      2
32     33              COL Colômbia     0      1       0      1
33     33       CIV Costa do Marfim     0      1       0      1
34     33                 EGY Egito     0      1       0      1
35     33               IRL Irlanda     0      1       0      1
36     33                  PER Peru     0      1       0      1
37     33                 SYR Síria     0      1       0      1
38     33             THA Tailândia     0      1       0      1
39     40               TUR Turquia     0      0       3      3
40     40             VEN Venezuela     0      0       3      3
41     42               ALG Argélia     0      0       2      2
42     43              CMR Camarões     0      0       1      1
43     43          TPE Taipé Chinês     0      0       1      1
44     43  DOM República Dominicana     0      0       1      1
45     43              ISL Islândia     0      0       1      1
46     43                ZAM Zâmbia     0      0       1      1

**Jogos Olímpicos de Verão de 1988 (corea do sul)**

In [48]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_1988 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_1988"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_1988, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_1988 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1988 = df_1988.iloc[:, :6]
df_1988.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1988 = df_1988.fillna(0)
df_1988 = df_1988[df_1988['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_1988[colunas_num] = df_1988[colunas_num].astype(int)

df_1988['País'] = df_1988['País'].str.strip()

df_1988.to_csv("medalhas_seul_1988.csv", index=False, sep=',', encoding='utf-8-sig')

df_1988

    Ordem                          País  Ouro  Prata  Bronze  Total
0       1           URS União Soviética    55     31      46    132
1       2         GDR Alemanha Oriental    37     35      30    102
2       3            USA Estados Unidos    36     31      27     94
3       4             KOR Coreia do Sul    12     10      11     33
4       5        FRG Alemanha Ocidental    11     14      15     40
5       6                   HUN Hungria    11      6       6     23
6       7                  BUL Bulgária    10     12      13     35
7       8                   ROM Romênia     7     11       6     24
8       9                    FRA França     6      4       6     16
9      10                    ITA Itália     6      4       4     14
10     11                     CHN China     5     11      12     28
11     12              GBR Grã-Bretanha     5     10       9     24
12     13                    KEN Quênia     5      2       2      9
13     14                     JPN Japão     4      3       7     14
14     15                 AUS Austrália     3      6       5     14
15     16                YUG Iugoslávia     3      4       5     12
16     17            TCH Checoslováquia     3      3       2      8
17     18             NZL Nova Zelândia     3      2       8     13
18     19                    CAN Canadá     3      2       5      9
19     20                   POL Polônia     2      5       9     16
20     21                   NOR Noruega     2      3       0      5
21     22             NED Países Baixos     2      2       5      9
22     23                 DEN Dinamarca     2      1       1      4
23     24                    BRA Brasil     1      2       3      6
24     25                   ESP Espanha     1      1       2      4
25     25                 FIN Finlândia     1      1       2      4
26     27                   TUR Turquia     1      1       0      2
27     28                  MAR Marrocos     1      0       2      3
28     29                   AUT Áustria     1      0       0      1
29     29                  POR Portugal     1      0       0      1
30     29                  SUR Suriname     1      0       0      1
31     32                    SWE Suécia     0      4       7     11
32     33                     SUI Suíça     0      2       2      4
33     34                   JAM Jamaica     0      2       0      2
34     35                 ARG Argentina     0      1       1      1
35     36     AHO Antilhas Neerlandesas     0      1       0      1
36     36                     CHI Chile     0      1       0      1
37     36                CRC Costa Rica     0      1       0      1
38     36  ISV Ilhas Virgens Americanas     0      1       0      1
39     36                 INA Indonésia     0      1       0      1
40     36                       IRI Irã     0      1       0      1
41     36                      PER Peru     0      1       0      1
42     36                   SEN Senegal     0      1       0      1
43     44                   BEL Bélgica     0      0       2      2
44     44                    MEX México     0      0       2      2
45     46                  COL Colômbia     0      0       1      1
46     46                   DJI Djibuti     0      0       1      1
47     46                 PHI Filipinas     0      0       1      1
48     46                    GRE Grécia     0      0       1      1
49     46                  MGL Mongólia     0      0       1      1
50     46                 PAK Paquistão     0      0       1      1
51     46                 THA Tailândia     0      0       1      1

**Jogos Olímpicos de Verão de 1992 - Espanha**

In [37]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_1992 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_1992"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_1992, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')

tabela_html = soup.find("table", {"class": "wikitable"})

df_1992 = pd.read_html(io.StringIO(str(tabela_html)))[0]
df_1992.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']
df_1992 = df_1992.fillna(0)
df_1992 = df_1992[df_1992['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_1992[colunas_num] = df_1992[colunas_num].astype(int)

df_1992['País'] = df_1992['País'].str.strip()

df_1992.to_csv("medalhas_barcelona_1992.csv", index=False, sep=',', encoding='utf-8-sig')
pd.set_option('display.max_rows', None)
df_1992

,Ordem,País,Ouro,Prata,Bronze,Total
0,1,EUN Equipa Unificada,45,38,29,112
1,2,USA Estados Unidos,37,34,37,108
2,3,GER Alemanha,33,21,28,82
3,4,CHN China,16,22,16,54
4,5,CUB Cuba,14,6,11,31
5,6,ESP Espanha,13,7,2,22
6,7,KOR Coreia do Sul,12,5,12,29
7,8,HUN Hungria,11,12,7,30
8,9,FRA França,8,5,16,29
9,10,AUS Austrália,7,9,11,27
10,11,CAN Canadá,7,4,7,18
11,12,ITA Itália,6,5,8,19
12,13,GBR Grã-Bretanha,5,3,12,20
13,14,ROU Romênia,4,6,8,18
14,15,TCH Checoslováquia,4,2,1,7
15,16,PRK Coreia do Norte,4,0,5,9
16,17,JPN Japão,3,8,11,22
17,18,BUL Bulgária,3,7,6,16
18,19,POL Polônia,3,6,10,19
19,20,NED Países Baixos,2,6,7,15
20,21,KEN Quênia,2,4,2,8
21,22,NOR Noruega,2,4,1,7
22,23,TUR Turquia,2,2,2,6
23,24,INA Indonésia,2,2,1,5
24,25,BRA Brasil,2,1,0,3
25,26,GRE Grécia,2,0,0,2
26,27,SWE Suécia,1,7,4,12
27,28,NZL Nova Zelândia,1,4,5,10
28,29,FIN Finlândia,1,2,2,5
29,30,DEN Dinamarca,1,1,4,6
30,31,MAR Marrocos,1,1,1,3
31,32,IRL Irlanda,1,1,0,2
32,33,ETH Etiópia,1,0,2,3
33,34,ALG Argélia,1,0,1,2
34,34,EST Estônia,1,0,1,2
35,34,LTU Lituânia,1,0,1,2
36,37,SUI Suíça,1,0,0,1
37,38,JAM Jamaica,0,3,1,4
38,38,NGR Nigéria,0,3,1,4
39,40,LAT Letônia,0,2,1,3
40,41,AUT Áustria,0,2,0,2
41,41,NAM Namíbia,0,2,0,2
42,41,RSA África do Sul,0,2,0,2
43,44,BEL Bélgica,0,1,2,3
44,44,CRO Croácia,0,1,2,3
45,44,IOP Participantes Olímpicos Independentes,0,1,2,3
46,44,IRI Irã,0,1,2,3
47,48,ISR Israel,0,1,1,2
48,49,TPE Taipé Chinês,0,1,0,1
49,49,MEX México,0,1,0,1
50,49,PER Peru,0,1,0,1
51,52,MGL Mongólia,0,0,2,2
52,52,SLO Eslovênia,0,0,2,2
53,54,ARG Argentina,0,0,1,1
54,54,BAH Bahamas,0,0,1,1
55,54,COL Colômbia,0,0,1,1
56,54,GHA Gana,0,0,1,1
57,54,MAS Malásia,0,0,1,1
58,54,PAK Paquistão,0,0,1,1
59,54,PHI Filipinas,0,0,1,1
60,54,PUR Porto Rico,0,0,1,1
61,54,QAT Catar,0,0,1,1
62,54,SUR Suriname,0,0,1,1
63,54,THA Tailândia,0,0,1,1

**jogos Olímpicos de Verão de 1996 - EUA**

In [38]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_1996 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_1996"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_1996, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')

tabela_html = soup.find("table", {"class": "wikitable"})

df_1996 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1996.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1996 = df_1996.fillna(0)

df_1996 = df_1996[df_1996['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']

df_1996[colunas_num] = df_1996[colunas_num].astype(int)
df_1996['País'] = df_1996['País'].str.strip()
df_1996.to_csv("medalhas_atlanta_1996.csv", index=False, sep=',', encoding='utf-8-sig')

df_1996

    Ordem                   País  Ouro  Prata  Bronze  Total
0       1     USA Estados Unidos    44     32      25    101
1       2             RUS Rússia    26     21      16     63
2       3           GER Alemanha    20     18      27     65
3       4              CHN China    16     22      12     50
4       5             FRA França    15      7      15     37
5       6             ITA Itália    13     10      12     35
6       7          AUS Austrália     9      9      23     41
7       8               CUB Cuba     9      8       8     25
8       9            UKR Ucrânia     9      2      12     23
9      10      KOR Coreia do Sul     7     15       5     27
10     11            POL Polônia     7      5       5     17
11     12            HUN Hungria     7      4      10     21
12     13            ESP Espanha     5      6       6     17
13     14            ROU Romênia     4      7       9     20
14     15      NED Países Baixos     4      5      10     19
15     16             GRE Grécia     4      4       0      8
16     17    CZE República Checa     4      3       4     11
17     18              SUI Suíça     4      3       0      7
18     19          DEN Dinamarca     4      1       1      6
19     19            TUR Turquia     4      1       1      6
20     21             CAN Canadá     3     11       8     22
21     22           BUL Bulgária     3      7       5     15
22     23              JPN Japão     3      6       5     14
23     24        KAZ Cazaquistão     3      4       4     11
24     25             BRA Brasil     3      3       9     15
25     26      NZL Nova Zelândia     3      2       1      6
26     27      RSA África do Sul     3      1       1      5
27     28            IRL Irlanda     3      0       1      4
28     29             SWE Suécia     2      4       2      8
29     30            NOR Noruega     2      2       3      7
30     31            BEL Bélgica     2      2       2      6
31     32            NGR Nigéria     2      1       3      6
32     33    PRK Coreia do Norte     2      1       2      5
33     34            ALG Argélia     2      0       1      3
34     34            ETH Etiópia     2      0       1      3
35     36       GBR Grã-Bretanha     1      8       6     15
36     37       BLR Bielorrússia     1      6       8     15
37     38             KEN Quênia     1      4       3      8
38     39            JAM Jamaica     1      3       2      6
39     40          FIN Finlândia     1      2       1      4
40     41          INA Indonésia     1      1       2      4
41     41         YUG Iugoslávia     1      1       2      4
42     43                IRI Irã     1      1       1      3
43     43         SVK Eslováquia     1      1       1      3
44     45            ARM Armênia     1      1       0      2
45     45            CRO Croácia     1      1       0      2
46     47           POR Portugal     1      0       1      2
47     47          THA Tailândia     1      0       1      2
48     49            BDI Burundi     1      0       0      1
49     49         CRC Costa Rica     1      0       0      1
50     49            ECU Equador     1      0       0      1
51     49          HKG Hong Kong     1      0       0      1
52     49              SYR Síria     1      0       0      1
53     54          ARG Argentina     0      2       1      3
54     55            NAM Namíbia     0      2       0      2
55     55          SLO Eslovênia     0      2       0      2
56     57            AUT Áustria     0      1       2      3
57     58            MAS Malásia     0      1       1      2
58     58           MDA Moldávia     0      1       1      2
59     58        UZB Uzbequistão     0      1       1      2
60     61         AZE Azerbaijão     0      1       0      1
61     61            BAH Bahamas     0      1       0      1
62     61       TPE Taipé Chinês     0      1       0      1
63     61            LAT Letônia     0      1       0      1
64     61          PHI Filipinas     0      1       0      1
65     61              TGA Tonga     0      1       0      1
66     61             ZAM Zâmbia     0      1       0      1
67     68            GEO Geórgia     0      0       2      2
68     68           MAR Marrocos     0      0       2      2
69     68  TRI Trinidad e Tobago     0      0       2      2
70     71              IND Índia     0      0       1      1
71     71             ISR Israel     0      0       1      1
72     71           LTU Lituânia     0      0       1      1
73     71             MEX México     0      0       1      1
74     71           MGL Mongólia     0      0       1      1
75     71         MOZ Moçambique     0      0       1      1
76     71         PUR Porto Rico     0      0       1      1
77     71            TUN Tunísia     0      0       1      1
78     71             UGA Uganda     0      0       1      1

**Jogos Olímpicos de Verão de 2000 -  Austrália**

In [39]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_2000 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_2000"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_2000, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_2000 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_2000.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']
df_2000 = df_2000.fillna(0)
df_2000 = df_2000[df_2000['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_2000[colunas_num] = df_2000[colunas_num].astype(int)

df_2000['País'] = df_2000['País'].str.strip()

df_2000.to_csv("medalhas_sydney_2000.csv", index=False, sep=',', encoding='utf-8-sig')

df_2000

   Ordem                        País  Ouro  Prata  Bronze  Total
0      1          USA Estados Unidos    37     24      32     93
1      2                  RUS Rússia    32     28      29     89
2      3                   CHN China    28     16      14     58
3      4               AUS Austrália    16     25      17     58
4      5                GER Alemanha    13     17      26     56
5      6                  FRA França    13     14      11     38
6      7                  ITA Itália    13      8      13     34
7      8           NED Países Baixos    12      9       4     25
8      9                    CUB Cuba    11     11       7     29
9     10            GBR Grã-Bretanha    11     10       7     28
10    11                 ROU Romênia    11      6       9     26
11    12           KOR Coreia do Sul     8     10      10     28
12    13                 HUN Hungria     8      6       3     17
13    14                 POL Polônia     6      5       3     14
14    15                   JPN Japão     5      8       5     18
15    16                BUL Bulgária     5      6       2     13
16    17                  GRE Grécia     4      6       3     13
17    18                  SWE Suécia     4      5       3     12
18    19                 NOR Noruega     4      3       3     10
19    20                 ETH Etiópia     4      1       3      8
20    21                 UKR Ucrânia     3     10      10     23
21    22             KAZ Cazaquistão     3      4       0      7
22    23            BLR Bielorrússia     3      3      11     17
23    24                  CAN Canadá     3      3       8     14
24    25                 ESP Espanha     3      3       5     11
25    26                 TUR Turquia     3      0       2      5
26    27                     IRI Irã     3      0       1      4
27    28         CZE República Checa     2      3       3      8
28    29                  KEN Quênia     2      3       2      7
29    30               DEN Dinamarca     2      3       1      6
30    31               FIN Finlândia     2      1       1      4
31    32                 AUT Áustria     2      1       0      3
32    33                LTU Lituânia     2      0       3      5
33    34              AZE Azerbaijão     2      0       1      3
34    34                 BAH Bahamas     2      0       1      3
35    36               SLO Eslovênia     2      0       0      2
36    37                   SUI Suíça     1      6       2      9
37    38               INA Indonésia     1      3       2      6
38    39              SVK Eslováquia     1      3       1      5
39    40                  MEX México     1      2       3      6
40    41                 NGR Nigéria     1      2       0      3
41    42                 ALG Argélia     1      1       3      5
42    43             UZB Uzbequistão     1      1       2      4
43    44                 LAT Letônia     1      1       1      3
44    44              YUG Iugoslávia     1      1       1      3
45    46           NZL Nova Zelândia     1      0       3      4
46    47                 EST Estônia     1      0       2      3
47    47               THA Tailândia     1      0       2      3
48    49                 CRO Croácia     1      0       1      2
49    50                CMR Camarões     1      0       0      1
50    50                COL Colômbia     1      0       0      1
51    50              MOZ Moçambique     1      0       0      1
52    53                  BRA Brasil     0      6       6     12
53    54                 JAM Jamaica     0      6       3      9
54    55                 BEL Bélgica     0      2       3      5
55    55           RSA África do Sul     0      2       3      5
56    57               ARG Argentina     0      2       2      4
57    58            TPE Taipé Chinês     0      1       4      5
58    58                MAR Marrocos     0      1       4      5
59    60         PRK Coreia do Norte     0      1       3      4
60    61                MDA Moldávia     0      1       1      2
61    61          KSA Arábia Saudita     0      1       1      2
62    61       TRI Trinidad e Tobago     0      1       1      2
63    64                 IRL Irlanda     0      1       0      1
64    64               SRI Sri Lanka     0      1       0      1
65    64                 URU Uruguai     0      1       0      1
66    64                  VIE Vietnã     0      1       0      1
67    68                 GEO Geórgia     0      0       6      6
68    69              CRC Costa Rica     0      0       2      2
69    69                POR Portugal     0      0       2      2
70    71                 ARM Armênia     0      0       1      1
71    71                BAR Barbados     0      0       1      1
72    71                   CHI Chile     0      0       1      1
73    71                ISL Islândia     0      0       1      1
74    71                   IND Índia     0      0       1      1
75    71                  ISR Israel     0      0       1      1
76    71                  KUW Kuwait     0      0       1      1
77    71             KGZ Quirguistão     0      0       1      1
78    71  MKD República da Macedônia     0      0       1      1
79    71                   QAT Catar     0      0       1      1

**Jogos Olímpicos de Verão de 2004 - Grécia**

In [42]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_2004 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_2004"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_2004, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_2004 = pd.read_html(io.StringIO(str(tabela_html)))[0]

# Ajuste para ignorar colunas extras de referências que causam o erro
df_2004 = df_2004.iloc[:, :6]
df_2004.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_2004 = df_2004.fillna(0)
df_2004 = df_2004[df_2004['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_2004[colunas_num] = df_2004[colunas_num].astype(int)

df_2004['País'] = df_2004['País'].str.strip()

df_2004.to_csv("medalhas_atenas_2004.csv", index=False, sep=',', encoding='utf-8-sig')

df_2004

   Ordem                        País  Ouro  Prata  Bronze  Total
0      1          USA Estados Unidos    36     39      26    101
1      2                   CHN China    32     17      14     63
2      3                  RUS Rússia    28     26      36     90
3      4               AUS Austrália    17     16      17     50
4      5                   JPN Japão    16      9      12     37
5      6                GER Alemanha    13     16      20     49
6      7                  FRA França    11      9      13     33
7      8                  ITA Itália    10     11      11     32
8      9           KOR Coreia do Sul     9     12       9     30
9     10            GBR Grã-Bretanha     9      9      12     30
10    11                    CUB Cuba     9      7      11     27
11    12                 HUN Hungria     8      6       3     17
12    13                 UKR Ucrânia     8      5       9     22
13    14                 ROU Romênia     8      5       6     19
14    15                  GRE Grécia     6      6       4     16
15    16                  BRA Brasil     5      2       3     10
16    17                 NOR Noruega     5      0       1      6
17    18           NED Países Baixos     4      9       9     22
18    19                  SWE Suécia     4      2       1      7
19    20                 ESP Espanha     3     11       6     20
20    21                  CAN Canadá     3      6       3     12
21    22                 TUR Turquia     3      3       5     11
22    23                 POL Polônia     3      2       5     10
23    24           NZL Nova Zelândia     3      2       0      5
24    25               THA Tailândia     3      1       4      8
25    26            BLR Bielorrússia     2      5       6     13
26    27                 AUT Áustria     2      4       1      7
27    28                 ETH Etiópia     2      3       2      7
28    29                     IRI Irã     2      2       2      6
29    29              SVK Eslováquia     2      2       2      6
30    31            TPE Taipé Chinês     2      2       1      5
31    32                 GEO Geórgia     2      2       0      4
32    33                BUL Bulgária     2      1       9     12
33    34               DEN Dinamarca     2      1       5      8
34    35                 JAM Jamaica     2      1       2      5
35    35             UZB Uzbequistão     2      1       2      5
36    37                MAR Marrocos     2      1       0      3
37    38               ARG Argentina     2      0       4      6
38    39                   CHI Chile     2      0       1      3
39    40             KAZ Cazaquistão     1      4       3      8
40    41                  KEN Quênia     1      4       2      7
41    42         CZE República Checa     1      3       5      9
42    43           RSA África do Sul     1      3       2      6
43    44                 CRO Croácia     1      2       2      5
44    45                LTU Lituânia     1      2       0      3
45    46                   EGY Egito     1      1       3      5
46    46                   SUI Suíça     1      1       3      5
47    48               INA Indonésia     1      1       2      4
48    49                ZIM Zimbabwe     1      1       1      3
49    50              AZE Azerbaijão     1      0       4      5
50    51                 BEL Bélgica     1      0       2      3
51    52                 BAH Bahamas     1      0       1      2
52    52                  ISR Israel     1      0       1      2
53    54                CMR Camarões     1      0       0      1
54    54    DOM República Dominicana     1      0       0      1
55    54  UAE Emirados Árabes Unidos     1      0       0      1
56    57         PRK Coreia do Norte     0      4       1      5
57    58                 LAT Letônia     0      4       0      4
58    59                  MEX México     0      3       1      4
59    60                POR Portugal     0      2       1      3
60    61               FIN Finlândia     0      2       0      2
61    61     SCG Sérvia e Montenegro     0      2       0      2
62    63               SLO Eslovênia     0      1       3      4
63    64                 EST Estônia     0      1       2      3
64    65               HKG Hong Kong     0      1       0      1
65    65                   IND Índia     0      1       0      1
66    65                PAR Paraguai     0      1       0      1
67    68                COL Colômbia     0      0       2      2
68    68                 NGR Nigéria     0      0       2      2
69    68               VEN Venezuela     0      0       2      2
70    71                ERI Eritreia     0      0       1      1
71    71                MGL Mongólia     0      0       1      1
72    71                   SYR Síria     0      0       1      1
73    71       TRI Trinidad e Tobago     0      0       1      1

**Jogos Olímpicos de Verão de 2008 - China**

In [43]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_2008 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_2008"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_2008, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_2008 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_2008 = df_2008.iloc[:, :6]
df_2008.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_2008 = df_2008.fillna(0)
df_2008 = df_2008[df_2008['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_2008[colunas_num] = df_2008[colunas_num].astype(int)

df_2008['País'] = df_2008['País'].str.strip()

df_2008.to_csv("medalhas_pequim_2008.csv", index=False, sep=',', encoding='utf-8-sig')

df_2008

   Ordem                      País  Ouro  Prata  Bronze  Total
0      1                 CHN China    48     22      30    100
1      2        USA Estados Unidos    36     39      37    112
2      3                RUS Rússia    24     13      23     60
3      4          GBR Grã-Bretanha    19     13      19     51
4      5              GER Alemanha    16     11      14     41
5      6             AUS Austrália    14     15      17     46
6      7         KOR Coreia do Sul    13     11       8     32
7      8                 JPN Japão     9      8       8     25
8      9                ITA Itália     8      9      10     27
9     10                FRA França     7     16      20     43
10    11         NED Países Baixos     7      5       4     16
11    12               UKR Ucrânia     7      4      11     22
12    13                KEN Quênia     6      4       6     16
13    14               ESP Espanha     5     11       3     19
14    15               JAM Jamaica     5      4       2     11
15    16               POL Polônia     4      5       2     11
16    17               ETH Etiópia     4      2       1      7
17    18               ROU Romênia     4      1       4      9
18    19                  CUB Cuba     3     10      17     30
19    20                CAN Canadá     3      9       8     20
20    21               HUN Hungria     3      5       2     10
21    22               NOR Noruega     3      5       1      9
22    23                BRA Brasil     3      4      10     17
23    24          BLR Bielorrússia     3      4       7     14
24    25       CZE República Checa     3      3       1      7
25    26            SVK Eslováquia     3      3       0      6
26    27         NZL Nova Zelândia     3      2       4      9
27    28               GEO Geórgia     3      2       2      7
28    29           KAZ Cazaquistão     2      3       4      9
29    30             DEN Dinamarca     2      2       3      7
30    31       PRK Coreia do Norte     2      2       2      6
31     0             THA Tailândia     2      2       2      6
32    33              MGL Mongólia     2      2       0      4
33    34                 SUI Suíça     2      1       4      7
34    35             ARG Argentina     2      0       4      6
35    36                MEX México     2      0       2      4
36    37               BEL Bélgica     2      0       0      2
37    38              ZIM Zimbabwe     1      3       0      4
38    39             SLO Eslovênia     1      2       2      5
39    40            AZE Azerbaijão     1      1       4      6
40     0             INA Indonésia     1      1       4      6
41    42              BUL Bulgária     1      1       3      5
42     0               TUR Turquia     1      1       3      5
43    44             FIN Finlândia     1      1       2      4
44     0          TPE Taipé Chinês     1      1       2      4
45    46               LAT Letônia     1      1       1      3
46    47  DOM República Dominicana     1      1       0      2
47     0               EST Estônia     1      1       0      2
48     0              POR Portugal     1      1       0      2
49     0     TRI Trinidad e Tobago     1      1       0      2
50    51                 IND Índia     1      0       2      3
51    52                   IRI Irã     1      0       1      2
52    53              CMR Camarões     1      0       0      1
53     0                PAN Panamá     1      0       0      1
54     0               TUN Tunísia     1      0       0      1
55    56                SWE Suécia     0      4       1      5
56    57              LTU Lituânia     0      3       2      5
57     0               NGR Nigéria     0      3       2      5
58    59               CRO Croácia     0      2       3      5
59    60              COL Colômbia     0      2       1      3
60     0                GRE Grécia     0      2       1      3
61    62               ARM Armênia     0      1       4      5
62    63           UZB Uzbequistão     0      1       3      4
63    64               AUT Áustria     0      1       2      3
64     0               IRL Irlanda     0      1       2      3
65     0           KGZ Quirguistão     0      1       2      3
66     0                SRB Sérvia     0      1       2      3
67    68               ALG Argélia     0      1       1      2
68     0               BAH Bahamas     0      1       1      2
69     0              MAR Marrocos     0      1       1      2
70     0           TJK Tajiquistão     0      1       1      2
71    72         RSA África do Sul     0      1       0      1
72     0                 CHI Chile     0      1       0      1
73     0               ECU Equador     0      1       0      1
74     0              ISL Islândia     0      1       0      1
75     0               MAS Malásia     0      1       0      1
76     0                 SAM Samoa     0      1       0      1
77     0             SIN Singapura     0      1       0      1
78     0                 SUD Sudão     0      1       0      1
79     0                VIE Vietnã     0      1       0      1
80    81                 EGY Egito     0      0       2      2
81    82           AFG Afeganistão     0      0       1      1
82     0                ISR Israel     0      0       1      1
83     0              MRI Maurício     0      0       1      1
84     0              MDA Moldávia     0      0       1      1
85     0                  TOG Togo     0      0       1      1
86     0             VEN Venezuela     0      0       1      1

**Jogos Olímpicos de Verão de 2012 - Grã-Bretanha**

In [44]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_2012 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_2012"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_2012, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_2012 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_2012 = df_2012.iloc[:, :6]
df_2012.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_2012 = df_2012.fillna(0)
df_2012 = df_2012[df_2012['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_2012[colunas_num] = df_2012[colunas_num].astype(int)

df_2012['País'] = df_2012['País'].str.strip()

df_2012.to_csv("medalhas_londres_2012.csv", index=False, sep=',', encoding='utf-8-sig')

df_2012

   Ordem                      País  Ouro  Prata  Bronze  Total
0      1        USA Estados Unidos    48     26      31    105
1      2                 CHN China    39     31      22     92
2      3          GBR Grã-Bretanha    29     18      18     65
3      4                RUS Rússia    18     20      26     64
4      5         KOR Coreia do Sul    13      9       9     31
5      6              GER Alemanha    11     20      13     44
6      7                FRA França    11     11      13     35
7      8             AUS Austrália     8     15      12     35
8      9                ITA Itália     8      9      11     28
9     10               HUN Hungria     8      4       6     18
10    11                 JPN Japão     7     14      17     38
11    12                   IRI Irã     7      5       1     13
12    13         NED Países Baixos     6      6       8     20
13    14         NZL Nova Zelândia     6      2       5     13
14    15               UKR Ucrânia     5      4      10     19
15    16                  CUB Cuba     5      3       7     15
16    17               ESP Espanha     4     10       6     20
17    18               JAM Jamaica     4      5       4     13
18    19       CZE República Checa     4      4       3     11
19    20         RSA África do Sul     4      1       1      6
20    21       PRK Coreia do Norte     4      0       2      6
21    22                BRA Brasil     3      5       9     17
22    23               ETH Etiópia     3      3       2      8
23    24           KAZ Cazaquistão     3      2       6     11
24     0               POL Polônia     3      2       6     11
25    26               CRO Croácia     3      1       2      6
26    27                CAN Canadá     2      6      10     18
27    28          BLR Bielorrússia     2      5       3     10
28    29                KEN Quênia     2      4       7     13
29    30             DEN Dinamarca     2      4       3      9
30    31               ROU Romênia     2      4       1      7
31    32            AZE Azerbaijão     2      2       5      9
32    33                 SUI Suíça     2      2       0      4
33    34               NOR Noruega     2      1       1      4
34    35              LTU Lituânia     2      0       3      5
35    36               TUN Tunísia     2      0       1      3
36    37                SWE Suécia     1      4       3      8
37    38              COL Colômbia     1      3       5      9
38    39                MEX México     1      3       4      8
39    40               GEO Geórgia     1      2       3      6
40    41               IRL Irlanda     1      1       4      6
41    42             ARG Argentina     1      1       2      4
42     0             SLO Eslovênia     1      1       2      4
43     0                SRB Sérvia     1      1       2      4
44     0     TRI Trinidad e Tobago     1      1       2      4
45    46               TUR Turquia     1      1       1      3
46    47  DOM República Dominicana     1      1       0      2
47    48               LAT Letônia     1      0       1      2
48     0          TPE Taipé Chinês     1      0       1      2
49    50               ALG Argélia     1      0       0      1
50     0               BAH Bahamas     1      0       0      1
51     0                 BRN Barém     1      0       0      1
52     0               GRN Granada     1      0       0      1
53     0                UGA Uganda     1      0       0      1
54     0             VEN Venezuela     1      0       0      1
55    56                 EGY Egito     0      3       1      4
56    57                 IND Índia     0      2       4      6
57    58              MGL Mongólia     0      2       3      5
58    59             THA Tailândia     0      2       2      4
59    60              BUL Bulgária     0      2       1      3
60     0             FIN Finlândia     0      2       1      3
61     0             INA Indonésia     0      2       1      3
62    63            SVK Eslováquia     0      1       3      4
63    64               BEL Bélgica     0      1       2      3
64    65               ARM Armênia     0      1       1      2
65     0                 QAT Catar     0      1       1      2
66     0               EST Estônia     0      1       1      2
67     0               MAS Malásia     0      1       1      2
68     0            PUR Porto Rico     0      1       1      2
69    70              BOT Botsuana     0      1       0      1
70     0                CYP Chipre     0      1       0      1
71     0                 GAB Gabão     0      1       0      1
72     0             GUA Guatemala     0      1       0      1
73     0            MNE Montenegro     0      1       0      1
74     0              POR Portugal     0      1       0      1
75    76           UZB Uzbequistão     0      0       3      3
76    77                GRE Grécia     0      0       2      2
77     0             SIN Singapura     0      0       2      2
78    79           AFG Afeganistão     0      0       1      1
79     0        KSA Arábia Saudita     0      0       1      1
80     0              CMR Camarões     0      0       1      1
81     0             HKG Hong Kong     0      0       1      1
82     0                KUW Kuwait     0      0       1      1
83     0              MAR Marrocos     0      0       1      1
84     0           TJK Tajiquistão     0      0       1      1
85     0                VIE Vietnã     0      0       1      1

**Jogos Olímpicos de Verão de 2016 -Brasil**

In [45]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_2016 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_2016"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_2016, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_2016 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_2016 = df_2016.iloc[:, :6]
df_2016.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_2016 = df_2016.fillna(0)
df_2016 = df_2016[df_2016['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_2016[colunas_num] = df_2016[colunas_num].astype(int)

df_2016['País'] = df_2016['País'].str.strip()

df_2016.to_csv("medalhas_rio_2016.csv", index=False, sep=',', encoding='utf-8-sig')

df_2016

   Ordem                                 País  Ouro  Prata  Bronze  Total
0      1                   USA Estados Unidos    46     37      38    121
1      2                     GBR Grã-Bretanha    27     23      17     67
2      3                            CHN China    26     18      26     70
3      4                           RUS Rússia    19     17      20     56
4      5                         GER Alemanha    17     10      15     42
5      6                            JPN Japão    12      8      21     41
6      7                           FRA França    10     18      14     42
7      8                    KOR Coreia do Sul     9      3       9     21
8      9                           ITA Itália     8     12       8     28
9     10                        AUS Austrália     8     11      10     29
10    11                    NED Países Baixos     8      7       4     19
11    12                          HUN Hungria     8      3       4     15
12    13                           BRA Brasil     7      6       6     19
13    14                          ESP Espanha     7      4       6     17
14    15                           KEN Quênia     6      6       1     13
15    16                          JAM Jamaica     6      3       2     11
16    17                          CRO Croácia     5      3       2     10
17    18                             CUB Cuba     5      2       4     11
18    19                    NZL Nova Zelândia     4      9       5     18
19    20                           CAN Canadá     4      3      15     22
20    21                      UZB Uzbequistão     4      2       7     13
21    22                      KAZ Cazaquistão     3      5      10     18
22    23                         COL Colômbia     3      2       3      8
23    24                            SUI Suíça     3      2       2      7
24    25                              IRI Irã     3      1       4      8
25    26                           GRE Grécia     3      1       2      6
26    27                        ARG Argentina     3      1       0      4
27    28                        DEN Dinamarca     2      6       7     15
28    29                           SWE Suécia     2      6       3     11
29    30                    RSA África do Sul     2      6       2     10
30    31                          UKR Ucrânia     2      5       4     11
31    32                           SRB Sérvia     2      4       2      8
32    33                          POL Polônia     2      3       6     11
33    34                  PRK Coreia do Norte     2      3       2      7
34    35                          BEL Bélgica     2      2       2      6
35    35                        THA Tailândia     2      2       2      6
36    37                       SVK Eslováquia     2      2       0      4
37    38                          GEO Geórgia     2      1       4      7
38    39                       AZE Azerbaijão     1      7      10     18
39    40                     BLR Bielorrússia     1      4       4      9
40    41                          TUR Turquia     1      3       4      8
41    42                          ARM Armênia     1      3       0      4
42    43                  CZE República Checa     1      2       7     10
43    44                          ETH Etiópia     1      2       5      8
44    45                        SLO Eslovênia     1      2       1      4
45    46                        INA Indonésia     1      2       0      3
46    47                          ROU Romênia     1      1       2      4
47    48                            BRN Barém     1      1       0      2
48    48                           VIE Vietnã     1      1       0      2
49    50                     TPE Taipé Chinês     1      0       2      3
50    51                          BAH Bahamas     1      0       1      2
51    51                  CIV Costa do Marfim     1      0       1      2
52    51  IOA Atletas Olímpicos Independentes     1      0       1      2
53    54                             FIJ Fiji     1      0       0      1
54    54                         JOR Jordânia     1      0       0      1
55    54                           KOS Kosovo     1      0       0      1
56    54                       PUR Porto Rico     1      0       0      1
57    54                        SIN Singapura     1      0       0      1
58    54                      TJK Tajiquistão     1      0       0      1
59    60                          MAS Malásia     0      4       1      5
60    61                           MEX México     0      3       2      5
61    62                        VEN Venezuela     0      2       1      3
62    63                          ALG Argélia     0      2       0      2
63    64                          IRL Irlanda     0      2       0      2
64    65                         LTU Lituânia     0      1       3      4
65    66                         BUL Bulgária     0      1       2      3
66    67                            IND Índia     0      1       1      2
67    67                         MGL Mongólia     0      1       1      2
68    69                          BDI Burundi     0      1       0      1
69    69                          GRN Granada     0      1       0      1
70    69                            NIG Níger     0      1       0      1
71    69                        PHI Filipinas     0      1       0      1
72    69                            QAT Catar     0      1       0      1
73    74                          NOR Noruega     0      0       4      4
74    75                            EGY Egito     0      0       3      3
75    75                          TUN Tunísia     0      0       3      3
76    77                           ISR Israel     0      0       2      2
77    78                          AUT Áustria     0      0       1      1
78    78             DOM República Dominicana     0      0       1      1
79    78                          EST Estônia     0      0       1      1
80    78                        FIN Finlândia     0      0       1      1
81    78                         MAR Marrocos     0      0       1      1
82    78                          NGR Nigéria     0      0       1      1
83    78                         POR Portugal     0      0       1      1
84    78                TTO Trinidad e Tobago     0      0       1      1
85    78           UAE Emirados Árabes Unidos     0      0       1      1

**Jogos Olímpicos de Verão de 2020 - Japão**

In [46]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_2020 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_2020"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_2020, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_2020 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_2020 = df_2020.iloc[:, :6]
df_2020.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_2020 = df_2020.fillna(0)
df_2020 = df_2020[df_2020['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_2020[colunas_num] = df_2020[colunas_num].astype(int)

df_2020['País'] = df_2020['País'].str.strip()

df_2020.to_csv("medalhas_toquio_2020.csv", index=False, sep=',', encoding='utf-8-sig')

df_2020

   Ordem                      País  Ouro  Prata  Bronze  Total
0      1        USA Estados Unidos    39     41      33    113
1      2                 CHN China    38     32      19     89
2      3                 JPN Japão    27     14      17     58
3      4          GBR Grã-Bretanha    22     20      22     64
4      5                   ROC ROC    20     28      23     71
5      6             AUS Austrália    17      7      22     46
6      7         NED Países Baixos    10     12      14     36
7      8                FRA França    10     12      11     33
8      9              GER Alemanha    10     11      16     37
9     10                ITA Itália    10     10      20     40
10    11                CAN Canadá     7      7      10     24
11    12                BRA Brasil     7      6       8     21
12    13         NZL Nova Zelândia     7      6       7     20
13    14                  CUB Cuba     7      3       5     15
14    15               HUN Hungria     6      7       7     20
15    16         KOR Coreia do Sul     6      4      10     20
16    17               POL Polônia     4      5       5     14
17    18       CZE República Checa     4      4       3     11
18    19                KEN Quênia     4      4       2     10
19    20               NOR Noruega     4      2       2      8
20    21               JAM Jamaica     4      1       4      9
21    22               ESP Espanha     3      8       6     17
22    23                SWE Suécia     3      6       0      9
23    24                 SUI Suíça     3      4       6     13
24    25             DEN Dinamarca     3      4       4     11
25    26               CRO Croácia     3      3       2      8
26    27                   IRI Irã     3      2       2      7
27    28                SRB Sérvia     3      1       5      9
28    29               BEL Bélgica     3      1       3      7
29    30              BUL Bulgária     3      1       2      6
30    31             SLO Eslovênia     3      1       1      5
31    32           UZB Uzbequistão     3      0       2      5
32    33               GEO Geórgia     2      5       1      8
33    34          TPE Taipé Chinês     2      4       6     12
34    35               TUR Turquia     2      2       9     13
35    36                GRE Grécia     2      1       1      4
36    36                UGA Uganda     2      1       1      4
37    38               ECU Equador     2      1       0      3
38    39               IRL Irlanda     2      0       2      4
39    39                ISR Israel     2      0       2      4
40    41                 QAT Catar     2      0       1      3
41    42               BAH Bahamas     2      0       0      2
42    42                KOS Kosovo     2      0       0      2
43    44               UKR Ucrânia     1      6      12     19
44    45          BLR Bielorrússia     1      3       3      7
45    46               ROU Romênia     1      3       0      4
46    46             VEN Venezuela     1      3       0      4
47    48                 IND Índia     1      2       4      7
48    49             HKG Hong Kong     1      2       3      6
49    50             PHI Filipinas     1      2       1      4
50    50            SVK Eslováquia     1      2       1      4
51    52         RSA África do Sul     1      2       0      3
52    53               AUT Áustria     1      1       5      7
53    54                 EGY Egito     1      1       4      6
54    55             INA Indonésia     1      1       3      5
55    56               ETH Etiópia     1      1       2      4
56    56              POR Portugal     1      1       2      4
57    58               TUN Tunísia     1      1       0      2
58    59               EST Estônia     1      0       1      2
59    59                  FIJ Fiji     1      0       1      2
60    59               LAT Letônia     1      0       1      2
61    59             THA Tailândia     1      0       1      2
62    63              BER Bermudas     1      0       0      1
63    63              MAR Marrocos     1      0       0      1
64    63            PUR Porto Rico     1      0       0      1
65    66              COL Colômbia     0      4       1      5
66    67            AZE Azerbaijão     0      3       4      7
67    68  DOM República Dominicana     0      3       2      5
68    69               ARM Armênia     0      2       2      4
69    70           KGZ Quirguistão     0      2       1      3
70    71              MGL Mongólia     0      1       3      4
71    72             ARG Argentina     0      1       2      3
72    72            SMR San Marino     0      1       2      3
73    74              JOR Jordânia     0      1       1      2
74    74               MAS Malásia     0      1       1      2
75    74               NGR Nigéria     0      1       1      2
76    77                 BRN Barém     0      1       0      1
77    77        KSA Arábia Saudita     0      1       0      1
78    77              LTU Lituânia     0      1       0      1
79    77    MKD Macedônia do Norte     0      1       0      1
80    77               NAM Namíbia     0      1       0      1
81    77         TKM Turcomenistão     0      1       0      1
82    83           KAZ Cazaquistão     0      0       8      8
83    84                MEX México     0      0       4      4
84    85             FIN Finlândia     0      0       2      2
85    86              BOT Botsuana     0      0       1      1
86    86        BUR Burquina Fasso     0      0       1      1
87    86       CIV Costa do Marfim     0      0       1      1
88    86                  GHA Gana     0      0       1      1
89    86               GRN Granada     0      0       1      1
90    86                KUW Kuwait     0      0       1      1
91    86              MDA Moldávia     0      0       1      1
92    86                 SYR Síria     0      0       1      1

**jogos Olímpicos de Verão de 2024 - França**

In [47]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_2024 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão_de_2024"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_2024, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_2024 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_2024 = df_2024.iloc[:, :6]
df_2024.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_2024 = df_2024.fillna(0)
df_2024 = df_2024[df_2024['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_2024[colunas_num] = df_2024[colunas_num].astype(int)

df_2024['País'] = df_2024['País'].str.strip()

df_2024.to_csv("medalhas_paris_2024.csv", index=False, sep=',', encoding='utf-8-sig')

df_2024

   Ordem                               País  Ouro  Prata  Bronze  Total
0      1                 USA Estados Unidos    40     44      42    126
1      2                          CHN China    40     27      24     91
2      3                          JPN Japão    20     12      13     45
3      4                      AUS Austrália    18     19      16     53
4      5                         FRA França    16     26      22     64
5      6                  NED Países Baixos    15      7      12     34
6      7                   GBR Grã-Bretanha    14     22      29     65
7      8                  KOR Coreia do Sul    13      9      10     32
8      9                         ITA Itália    12     13      15     40
9     10                       GER Alemanha    12     13       8     33
10    11                  NZL Nova Zelândia    10      7       3     20
11    12                         CAN Canadá     9      7      11     27
12    13                    UZB Uzbequistão     8      2       3     13
13    14                        HUN Hungria     6      7       6     19
14    15                        ESP Espanha     5      4       9     18
15    16                         SWE Suécia     4      4       3     11
16    17                         KEN Quênia     4      2       5     11
17    18                        NOR Noruega     4      1       3      8
18    19                        IRL Irlanda     4      0       3      7
19    20                         BRA Brasil     3      7      10     20
20    21                            IRI Irã     3      6       3     12
21    22                        UKR Ucrânia     3      5       4     12
22    23                        ROU Romênia     3      4       2      9
23    24                        GEO Geórgia     3      3       1      7
24    25                        BEL Bélgica     3      1       6     10
25    26                       BUL Bulgária     3      1       3      7
26    27                         SRB Sérvia     3      1       1      5
27    28                        CZE Chéquia     3      0       2      5
28    29                      DEN Dinamarca     2      2       5      9
29    30                     AZE Azerbaijão     2      2       3      7
30    30                        CRO Croácia     2      2       3      7
31    32                           CUB Cuba     2      1       6      9
32    33                          BRN Barém     2      1       1      4
33    34                      SLO Eslovênia     2      1       0      3
34    35                   TPE Taipé Chinês     2      0       5      7
35    36                        AUT Áustria     2      0       3      5
36    37                      PHI Filipinas     2      0       2      4
37    37                      HKG Hong Kong     2      0       2      4
38    39                        ALG Argélia     2      0       1      3
39    39                      INA Indonésia     2      0       1      3
40    41                         ISR Israel     1      5       1      7
41    42                        POL Polônia     1      4       5     10
42    43                    KAZ Cazaquistão     1      3       3      7
43    44                  RSA África do Sul     1      3       2      6
44    44                        JAM Jamaica     1      3       2      6
45    44                      THA Tailândia     1      3       2      6
46     –    AIN Atletas Individuais Neutros     1      3       1      5
47    47                        ETH Etiópia     1      3       0      4
48    48                          SUI Suíça     1      2       5      8
49    49                        ECU Equador     1      2       2      5
50    50                       POR Portugal     1      2       1      4
51    51                         GRE Grécia     1      1       6      8
52    52                      ARG Argentina     1      1       1      3
53    52                          EGY Egito     1      1       1      3
54    52                        TUN Tunísia     1      1       1      3
55    55                       BOT Botsuana     1      1       0      2
56    55                          CHI Chile     1      1       0      2
57    55                    LCA Santa Lúcia     1      1       0      2
58    55                         UGA Uganda     1      1       0      2
59    59           DOM República Dominicana     1      0       2      3
60    60                      GUA Guatemala     1      0       1      2
61    60                       MAR Marrocos     1      0       1      2
62    62                       DMA Dominica     1      0       0      1
63    62                      PAK Paquistão     1      0       0      1
64    64                        TUR Turquia     0      3       5      8
65    65                         MEX México     0      3       2      5
66    66                        ARM Armênia     0      3       1      4
67    67                       COL Colômbia     0      3       1      4
68    68                PRK Coreia do Norte     0      2       4      6
69    68                    KGZ Quirguistão     0      2       4      6
70    70                       LTU Lituânia     0      2       2      4
71    71                          IND Índia     0      1       5      6
72    72                       MDA Moldávia     0      1       3      4
73    73                         KOS Kosovo     0      1       1      2
74    74                         CYP Chipre     0      1       0      1
75    74                           FIJ Fiji     0      1       0      1
76    74                       JOR Jordânia     0      1       0      1
77    74                       MGL Mongólia     0      1       0      1
78    74                         PAN Panamá     0      1       0      1
79    79                    TJK Tajiquistão     0      0       3      3
80    80                        ALB Albânia     0      0       2      2
81    80                        GRN Granada     0      0       2      2
82    80                        MAS Malásia     0      0       2      2
83    80                     PUR Porto Rico     0      0       2      2
84    84                     CPV Cabo Verde     0      0       1      1
85    84                          QAT Catar     0      0       1      1
86    84                CIV Costa do Marfim     0      0       1      1
87    84  EOR Equipe Olímpica de Refugiados     0      0       1      1
88    84                     SVK Eslováquia     0      0       1      1
89    84                           PER Peru     0      0       1      1
90    84                      SGP Singapura     0      0       1      1
91    84                         ZAM Zâmbia     0      0       1      1