**Jogos Paralímpicos de Verão de 1960 - Italia**

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_1960 = "https://pt.wikipedia.org/wiki/Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_1960"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_1960, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_1960 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_para_1960 = df_para_1960.iloc[:, :6]
df_para_1960.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_1960 = df_para_1960.fillna(0)
df_para_1960 = df_para_1960[df_para_1960['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_para_1960[colunas_num] = df_para_1960[colunas_num].astype(int)

df_para_1960['País'] = df_para_1960['País'].str.strip()

df_para_1960.to_csv("paralimpicos_roma_1960.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_1960

   Ordem                    País  Ouro  Prata  Bronze  Total
0      1              ITA Itália    29     28      23     80
1      2        GBR Grã-Bretanha    20     15      20     55
2      3  FRG Alemanha Ocidental    15      6       9     30
3      4             AUT Áustria    11      8      11     30
4      5      USA Estados Unidos    11      7       7     25
5      6             NOR Noruega     9      3       4     16
6      7           AUS Austrália     3      6       1     10
7      8       NED Países Baixos     3      6       0      9
8      9              FRA França     3      3       1      7
9     10           ARG Argentina     2      3       1      6
10    11             RHO Rodésia     2      1       2      5
11    12             IRL Irlanda     2      0       0      2
12    13               SUI Suíça     1      3       0      4
13    14             BEL Bélgica     1      1       1      3
14    15           FIN Finlândia     1      0       0      1
15    16              ISR Israel     0      2       2      4
16    17               MLT Malta     0      2       2      4

**Paralímpicos de Verão de 1964 - Japão**

In [3]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_1964 = "https://pt.wikipedia.org/wiki/Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_1964"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_1964, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_1964 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_para_1964 = df_para_1964.iloc[:, :6]
df_para_1964.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_1964 = df_para_1964.fillna(0)
df_para_1964 = df_para_1964[df_para_1964['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_para_1964[colunas_num] = df_para_1964[colunas_num].astype(int)

df_para_1964['País'] = df_para_1964['País'].str.strip()

df_para_1964.to_csv("paralimpicos_toquio_1964.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_1964

    Ordem                País  Ouro  Prata  Bronze  Total
0       1      Estados Unidos    50     41      32    123
1       2         Reino Unido    18     23      20     61
2       3              Itália    14     15      16     45
3       4           Austrália    12     11       7     30
4       5             Rodésia    10      5       2     17
5       6       África do Sul     8      8       3     19
6       7              Israel     7      3      11     21
7       8           Argentina     6     15      16     37
8       9  Alemanha Ocidental     5      2       5     12
9      10       Países Baixos     4      6       4     14
10     11              França     4      2       5     11
11     12             Áustria     4      1       7     12
12     13               Japão     1      5       4     10
13     14             Bélgica     1      0       2      3
14     15               Suíça     0      1       0      1
15     16               Malta     0      0       2      2
16     17              Suécia     0      0       1      1

**Jogos Paralímpicos de Verão de 1968 Tel Aviv**

In [4]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_1968 = "https://pt.wikipedia.org/wiki/Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_1968"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_1968, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_1968 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_para_1968 = df_para_1968.iloc[:, :6]
df_para_1968.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_1968 = df_para_1968.fillna(0)
df_para_1968 = df_para_1968[df_para_1968['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_para_1968[colunas_num] = df_para_1968[colunas_num].astype(int)

df_para_1968['País'] = df_para_1968['País'].str.strip()

df_para_1968.to_csv("paralimpicos_tel_aviv_1968.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_1968

    Ordem            País  Ouro  Prata  Bronze  Total
0       1  Estados Unidos    33     27      39     99
1       2     Reino Unido    29     20      20     69
2       3          Israel    18     21      23     62
3       4       Austrália    15     16       7     38
4       5          França    13     10       9     32
5       6        Alemanha    12     11      11     35
6       7          Itália    12     10      17     39
7       8   Países Baixos    12      4       4     20
8       9       Argentina    10     10      10     30
9      10   África do Sul     9     10       7     26
10     11         Rodésia     6      7       7     20
11     12          Canadá     6      6       7     19
12     13         Noruega     5      3       1      9
13     14         Jamaica     3      1       1      5
14     15         Áustria     2      7      11     19
15     16           Japão     2      2       8     12
16     17          Suécia     1      6       4     11
17     18   Nova Zelândia     1      2       1      4
18     19         Irlanda     0      4       5      9
19     20         Bélgica     0      3       3      6
20     21         Espanha     0      3       1      4
21     22           Suíça     0      2       6      8

**Jogos Paralímpicos de Verão de 1972 - Alemanha**

In [5]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_1972 = "https://pt.wikipedia.org/wiki/Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_1972"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_1972, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_1972 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_para_1972 = df_para_1972.iloc[:, :6]
df_para_1972.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_1972 = df_para_1972.fillna(0)
df_para_1972 = df_para_1972[df_para_1972['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_para_1972[colunas_num] = df_para_1972[colunas_num].astype(int)

df_para_1972['País'] = df_para_1972['País'].str.strip()

df_para_1972.to_csv("paralimpicos_heidelberg_1972.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_1972

    Ordem             País  Ouro  Prata  Bronze  Total
0       1         Alemanha    28     15      24     67
1       2   Estados Unidos    17     27      30     74
2       3      Reino Unido    16     15      21     52
3       4    África do Sul    16     12      13     41
4       5    Países Baixos    14     13      11     38
5       6          Polónia    14     12       7     33
6       7           França    10      8      12     30
7       8           Israel     9     10       9     28
8       9           Itália     8      4       5     17
9      10          Jamaica     8      3       4     15
10     11        Austrália     6      9      10     25
11     12          Áustria     6      6       6     18
12     13           Canadá     5      6       8     19
13     14           Suécia     5      6       6     17
14     15            Japão     4      5       3     12
15     16    Coreia do Sul     4      2       1      7
16     17          Rodésia     3      4       5     12
17     18    Nova Zelândia     3      3       3      9
18     19            Suíça     3      2       4      9
19     20        Argentina     2      4       3      9
20     21          Irlanda     2      4       2      8
21     22          Noruega     1      5       5     11
22     23          Bélgica     1      1       2      5
23     24       Iugoslávia     1      1       2      4
24     25            Índia     1      0       0      1
25     25           Quênia     1      0       0      1
26     27          Espanha     0      4       0      4
27     28        Finlândia     0      2       2      4
28     29        Hong Kong     0      1       1      2
29     30          Hungria     0      0       1      1
30     30  Tchecoslováquia     0      0       1      1

**Jogos Paralímpicos de Verão de 1976 - Canada**

In [6]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_1976 = "https://pt.wikipedia.org/wiki/Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_1976"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_1976, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_1976 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_para_1976 = df_para_1976.iloc[:, :6]
df_para_1976.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_1976 = df_para_1976.fillna(0)
df_para_1976 = df_para_1976[df_para_1976['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_para_1976[colunas_num] = df_para_1976[colunas_num].astype(int)

df_para_1976['País'] = df_para_1976['País'].str.strip()

df_para_1976.to_csv("paralimpicos_toronto_1976.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_1976

    Ordem                País  Ouro  Prata  Bronze  Total
0       1      Estados Unidos    66     43      45    154
1       2       Países Baixos    45     25      14     84
2       3              Israel    40     13      16     69
3       4  Alemanha Ocidental    37     34      26     97
4       5         Reino Unido    29     29      36     94
5       6              Canadá    25     27      26     78
6       7             Polónia    24     17      12     53
7       8              França    23     21      14     58
8       9              Suécia    22     27      24     73
9      10             Áustria    17     16      17     50
10     11           Austrália    16     18       8     42
11     12              México    16     14       9     39
12     13           Finlândia    12     20      18     50
13     14               Suíça    10     12      10     32
14     15               Japão    10      6       3     19
15     16             Noruega     9      6       4     19
16     17             Bélgica     7      7       8     25
17     18       Nova Zelândia     7      1       5     13
18     19       África do Sul     6      9      11     26
19     20               Egito     5      2       1      8
20     21             Irlanda     4     10       6     20
21     22             Espanha     4      6       2     12
22     23           Argentina     3      4       7     14
23     24           Dinamarca     3      0       3      6
24     25              Itália     2      5      11     18
25     26           Indonésia     2      1       4      7
26     27       Coreia do Sul     1      2       1      4
27     28             Myanmar     1      1       1      3
28     29                Peru     1      0       2      3
29     30           Hong Kong     0      1       2      3
30     31              Brasil     0      1       0      1
31     32           Guatemala     0      0       1      1

**Jogos Paralímpicos de Verão de 1980 - Holanda**

In [7]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_1980 = "https://pt.wikipedia.org/wiki/Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_1980"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_1980, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_1980 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_para_1980 = df_para_1980.iloc[:, :6]
df_para_1980.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_1980 = df_para_1980.fillna(0)
df_para_1980 = df_para_1980[df_para_1980['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_para_1980[colunas_num] = df_para_1980[colunas_num].astype(int)

df_para_1980['País'] = df_para_1980['País'].str.strip()

df_para_1980.to_csv("paralimpicos_arnhem_1980.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_1980

    Ordem                País  Ouro  Prata  Bronze  Total
0       1      Estados Unidos    75     66      54    195
1       2             Polónia    75     50      52    177
2       3  Alemanha Ocidental    67     48      46    161
3       4              Canadá    64     35      31    130
4       5         Reino Unido    47     32      20     99
5       6       Países Baixos    33     31      36    100
6       7              Suécia    30     36      24     90
7       8              França    28     26      31     85
8       9              México    20     16       6     42
9      10             Noruega    15     12       7     34
10     11             Áustria    14     23       8     45
11     12              Israel    13     18      15     46
12     13             Bélgica    13     11      17     41
13     14           Austrália    12     21      17     55
14     15               Suíça     9     10      10     29
15     16               Japão     9     10       7     26
16     17           Finlândia     7     19      13     39
17     18             Jamaica     7      7       5     19
18     19       Nova Zelândia     7      5       6     18
19     20              Itália     6      5       9     20
20     21           Dinamarca     6      4       7     17
21     22               Egito     4      7       3     14
22     23          Iugoslávia     4      5       9     18
23     24           Argentina     4      5       6     15
24     25             Irlanda     4      2      11     17
25     26       Coreia do Sul     2      2       1      5
26     27              Kuwait     2      2       1      5
27     28           Indonésia     2      0       4      6
28     29             Espanha     1     13       9     23
29     30              Quênia     1      2       0      3
30     31            Colômbia     1      0       1      2
31     32            Islândia     1      0       1      2
32     33            Alemanha     1      0       0      1
33     34               Sudão     1      0       0      1
34     35            Zimbabwe     0      8       4     12
35     36             Bahamas     0      1       2      3
36     37           Hong Kong     0      1       2      3
37     38     Tchecoslováquia     0      1       1      2
38     39              Grécia     0      0       1      1
39     40          Luxemburgo     0      0       1      1
40     41               Malta     0      0       1      1

**Paralimpíadas de Verão de 1984 foram realizados em Stoke Mandeville, Grã-Bretanha (atletas em cadeira de rodas) e em Nova Iorque, Estados Unidos
(atletas com paralisia cerebral, deficiências visuais, amputados e "outros")**

Stoke Mandeville foi a primeira sede dos Jogos de Stoke Mandeville de 1948, visto como o precursor dos Jogos Paralímpicos.

In [9]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_1984 = "https://pt.wikipedia.org/wiki/Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_1984"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_1984, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_1984 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_para_1984 = df_para_1984.iloc[:, :6]
df_para_1984.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_1984 = df_para_1984.fillna(0)
df_para_1984 = df_para_1984[df_para_1984['País'].str.contains('Total|TOTAL') == False]


colunas_num = ['Ordem', 'Ouro', 'Prata', 'Bronze', 'Total']
df_para_1984[colunas_num] = df_para_1984[colunas_num].apply(pd.to_numeric, errors='coerce').fillna(0).astype(int)

df_para_1984['País'] = df_para_1984['País'].str.strip()

df_para_1984.to_csv("paralimpicos_1984.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_1984

    Ordem                    País  Ouro  Prata  Bronze  Total
0       1      USA Estados Unidos   136    131     129    396
1       2        GBR Grã-Bretanha   107    112     112    331
2       3              CAN Canadá    87     82      69    238
3       4              SWE Suécia    80     43      34    157
4       5  FRG Alemanha Ocidental    79     76      74    229
5       6              FRA França    71     69      45    185
6       7       NED Países Baixos    55     51      28    134
7       8           AUS Austrália    49     54      51    154
8       9             POL Polônia    46     39      21    106
9      10           DEN Dinamarca    30     13      16     59
10     11             NOR Noruega    29     31      30     90
11     12             BEL Bélgica    22     21      14     57
12     13             ESP Espanha    22     10      12     44
13     14             IRL Irlanda    20     15      30     65
14     15           FIN Finlândia    19     13      26     58
15     16               SUI Suíça    18     13      12     43
16     17             AUT Áustria    14     20      10     44
17     18             HUN Hungria    12     12       4     28
18     19              ISR Israel    11     21      12     44
19     20          YUG Iugoslávia    11      9      11     31
20     21              ITA Itália     9     19      14     42
21     22               JPN Japão     9      7       8     24
22     23       NZL Nova Zelândia     8     10       7     25
23     24              BRA Brasil     7     17       4     28
24     25              MEX México     6     14      17     37
25     26            POR Portugal     4      3       7     14
26     27           HKG Hong Kong     3      5       9     17
27     28               CHN China     2     12       8     22
28     29   TRI Trinidad e Tobago     2      0       1      3
29     30          LUX Luxemburgo     1      4       1      6
30     31              KUW Kuwait     1      3       4      8
31     32            BIR Birmânia     1      2       1      4
32     33               EGY Egito     1      1       5      7
33     34              KEN Quênia     1      1       1      3
34     35   GDR Alemanha Oriental     0      3       1      4
35     36            ISL Islândia     0      2       8     10
36     37               IND Índia     0      2       2      4
37      0       KOR Coreia do Sul     0      2       2      4
38     39            JOR Jordânia     0      1       2      3
39      0            ZIM Zimbabwe     0      1       2      3
40     41             BAH Bahamas     0      1       1      2
41      0           INA Indonésia     0      1       1      2
42     43               BRN Barém     0      0       2      2

**Jogos Paralímpicos de Verão de 1988 - Corea**

In [10]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_1988 = "https://pt.wikipedia.org/wiki/Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_1988"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_1988, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_1988 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_para_1988 = df_para_1988.iloc[:, :6]
df_para_1988.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_1988 = df_para_1988.fillna(0)
df_para_1988 = df_para_1988[df_para_1988['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ordem', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_1988['País'] = df_para_1988['País'].str.strip()

df_para_1988.to_csv("paralimpicos_seul_1988.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_1988

    Ordem                País  Ouro  Prata  Bronze  Total
0       1      Estados Unidos    92     91      85    267
1       2  Alemanha Ocidental    77     64      48    189
2       3         Reino Unido    62     66      51    179
3       4              Canadá    54     42      57    153
4       5              França    45     48      49    142
5       6              Suécia    42     38      22    102
6       7       Coreia do Sul    40     35      19     94
7       8       Países Baixos    30     23      29     82
8       9           Dinamarca    25     18      22     65
9      10           Austrália    23     34      37     94
10     11             Polónia    22     25      34     81
11     12     União Soviética    21     19      15     55
12     13             Espanha    18     13      12     43
13     14               China    17     17       9     43
14     15              Itália    16     15      27     58
15     16               Japão    16     12      17     45
16     17             Bélgica    15     17       9     41
17     18              Israel    15     13      15     43
18     19             Irlanda    13     13      18     44
19     20             Áustria    13      7      15     35
20     21               Suíça    12     12      10     34
21     22           Finlândia    11     23      15     49
22     23             Noruega    11     11      13     35
23     24              México     8      9       6     23
24     25              Brasil     4      9      14     27
25     26              Kuwait     4      6       8     18
26     27          Iugoslávia     4      4      11     19
27     28                Irão     4      1       3      8
28     29            Portugal     3      4       5     12
29     30       Nova Zelândia     2      4      11     17
30     31            Islândia     2      2       8     12
31     32            Bulgária     2      1       0      3
32     33             Jamaica     1      4       3      8
33     34         Ilhas Feroé     1      3       3      7
34     35               Egito     1      2       3      6
35     36          Porto Rico     1      2       0      3
36     37               Barém     1      1       1      3
37     38           Guatemala     1      0       0      1
38     39           Argentina     0      7       2      9
39     40             Hungria     0      4       7     11
40     41              Quênia     0      4       1      5
41     42           Hong Kong     0      2       7      9
42     43              Grécia     0      1       3      4
43     44           Indonésia     0      1       0      1
44     44     Tchecoslováquia     0      1       0      1
45     44           Tailândia     0      1       0      1
46     47             Tunísia     0      0       2      2
47     48               Malta     0      0       1      1

**Jogos Paralímpicos de Verão de 1992 - Espanha**

In [11]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_1992 = "https://pt.wikipedia.org/wiki/Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_1992"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_1992, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_1992 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_para_1992 = df_para_1992.iloc[:, :6]
df_para_1992.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_1992 = df_para_1992.fillna(0)
df_para_1992 = df_para_1992[df_para_1992['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ordem', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_1992['País'] = df_para_1992['País'].str.strip()

df_para_1992.to_csv("paralimpicos_barcelona_1992.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_1992

,Ordem,País,Ouro,Prata,Bronze,Total
0,1,USA Estados Unidos,76,51,48,175
1,2,GER Alemanha,60,50,60,170
2,3,GBR Grã-Bretanha,40,46,41,127
3,4,FRA França,36,35,33,104
4,5,ESP Espanha,34,31,42,107
5,6,CAN Canadá,28,21,26,75
6,7,AUS Austrália,24,27,25,76
7,8,Equipe Unficada,17,15,15,47
8,9,NED Países Baixos,13,15,11,39
9,10,NOR Noruega,13,12,7,33
10,11,DEN Dinamarca,12,22,12,46
11,12,CHN China,11,7,7,25
12,13,KOR Coreia do Sul,10,14,18,42
13,14,ITA Itália,10,7,18,35
14,15,FIN Finlândia,8,6,11,25
15,16,POL Polônia,7,10,7,24
16,17,JPN Japão,7,8,15,30
17,18,SUI Suíça,6,16,12,34
18,19,SWE Suécia,5,22,8,35
19,20,AUT Áustria,5,4,13,22
20,21,BEL Bélgica,5,4,6,15
21,22,EGY Egito,5,4,4,13
22,23,NZL Nova Zelândia,5,1,0,6
23,24,TCH Checoslováquia,4,3,6,13
24,25,HUN Hungria,4,3,4,11
25,26,Participantes Paraolímpicos Independentes,4,3,1,8
26,27,RSA África do Sul,4,1,3,8
27,28,HKG Hong Kong,3,4,4,11
28,29,CUB Cuba,3,3,3,9
29,30,POR Portugal,3,3,1,7
30,31,ISL Islândia,3,2,12,17
31,32,BRA Brasil,3,0,4,7
32,33,ISR Israel,2,4,5,11
33,34,SLO Eslovênia,2,0,1,3
34,35,NGR Nigéria,2,0,0,2

**Jogos Paralímpicos de Verão de 1996 - EUA**

In [12]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_1996 = "https://pt.wikipedia.org/wiki/Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_1996"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_1996, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_1996 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_para_1996 = df_para_1996.iloc[:, :6]
df_para_1996.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_1996 = df_para_1996.fillna(0)
df_para_1996 = df_para_1996[df_para_1996['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ordem', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_1996['País'] = df_para_1996['País'].str.strip()

df_para_1996.to_csv("paralimpicos_atlanta_1996.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_1996

    Ordem            País  Ouro  Prata  Bronze  Total
0       1  Estados Unidos    46     46      65    157
1       2       Austrália    42     37      27    106
2       3        Alemanha    40     58      51    149
3       4     Reino Unido    39     42      41    122
4       5         Espanha    39     31      36    106
5       6          França    35     29      31     95
6       7          Canadá    24     21      24     69
7       8   Países Baixos    17     11      17     45
8       9           China    16     13      10     39
9      10           Japão    14     10      12     36
10     11         Polónia    13     14       8     35
11     12   Coreia do Sul    13      2      15     30
12     13          Suécia    12     14      10     36
13     14          Itália    11     20      15     46
14     15   África do Sul    10      8      10     28
15     16          Rússia     9      7      11     27
16     17         Noruega     9      7       4     20
17     18           Suíça     9      6       6     21
18     19   Nova Zelândia     9      6       3     18
19     20            Irão     9      5       3     17
20     21           Egito     8     11      11     30
21     22         Bélgica     8     10       7     25
22     23            Cuba     8      3       0     11
23     24       Dinamarca     7     17      17     41
24     25         Áustria     6      6      10     22
25     26    POR Portugal     6      4       4     14
26     27       Hong Kong     5      5       5     15
27     28        Islândia     5      4       5     14
28     29         Hungria     5      2       3     10
29     30       Finlândia     4      5       4     13
30     31          México     3      5       4     12
31     32         Estónia     3      4       2      9
32     33    Bielorrússia     3      3       7     13
33     34        Lituânia     3      2       6     11
34     35           Níger     3      2       3      8
35     36         Chéquia     2      7       1     10
36     37          Brasil     2      6      13     21
37     38       Argentina     2      5       2      9
38     39      Eslováquia     2      4       5     11
39     40         Argélia     2      2       3      7

**Jogos Paralímpicos de Verão de 2000 - Australia**

In [14]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_2000 = "https://pt.wikipedia.org/wiki/Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_2000"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_2000, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_2000 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_para_2000 = df_para_2000.iloc[:, :6]
df_para_2000.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_2000 = df_para_2000.fillna(0)
df_para_2000 = df_para_2000[df_para_2000['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ordem', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_2000['País'] = df_para_2000['País'].str.strip()

df_para_2000.to_csv("paralimpicos_sydney_2000.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_2000

    Ordem                País  Ouro  Prata  Bronze  Total
0       1       AUS Austrália    63     39      47    149
1       2    GBR Grã-Bretanha    41     43      47    131
2       3         ESP Espanha    39     30      38    107
3       4          CAN Canadá    38     33      25     96
4       5  USA Estados Unidos    36     39      34    109
5       6           CHN China    34     22      17     73
6       7          FRA França    30     28      28     86
7       8         POL Polônia    19     22      12     53
8       9   KOR Coreia do Sul    18      7       7     32
9      10        GER Alemanha    15     42      38     95
10     11         CZE Chéquia    15     15      13     43
11     12           JPN Japão    13     17      11     41
12     13   RSA África do Sul    13     12      13     38
13     14          RUS Rússia    12     11      12     35
14     15   NED Países Baixos    12      9       9     30
15     16             IRN Irã    12      4       7     23
16     17          MEX México    10     12      12     34
17     18          ITA Itália     9      8      10     27
18     19       DEN Dinamarca     8      8      14     30
19     20           SUI Suíça     8      4       8     20
20     21       HKG Hong Kong     8      3       7     18
21     22         NGR Nigéria     7      1       5     13
22     23           EGY Egito     6     11      11     28
23     24          BRA Brasil     6     10       6     22
24     25   NZL Nova Zelândia     6      8       4     18
25     26        POR Portugal     6      5       4     15

**Jogos Paralímpicos de Verão de 2004 - Grecia**

In [15]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_2004 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_2004"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_2004, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_2004 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_para_2004 = df_para_2004.iloc[:, :6]
df_para_2004.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_2004 = df_para_2004.fillna(0)
df_para_2004 = df_para_2004[df_para_2004['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ordem', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_2004['País'] = df_para_2004['País'].str.strip()

df_para_2004.to_csv("paralimpicos_atenas_2004.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_2004

    Ordem            País  Ouro  Prata  Bronze  Total
0       1           China    63     46      32    141
1       2    Grã-Bretanha    35     30      29     94
2       3          Canadá    28     19      25     72
3       4  Estados Unidos    27     22      39     88
4       5       Austrália    26     38      36    100
5       6         Ucrânia    24     12      19     55
6       7         Espanha    20     27      24     71
7       8        Alemanha    19     28      32     79
8       9          França    18     26      30     74
9      10           Japão    17     15      20     52
10     11          Rússia    16      8      17     41
11     12         Chéquia    16      8       7     31
12     13   África do Sul    15     13       7     35
13     14          Brasil    14     12       7     33
14     15          México    14     10      10     34
15     16   Coreia do Sul    11     11       6     28
16     17       Hong Kong    11      7       1     19
17     18         Polônia    10     25      19     54
18     19    Bielorrússia    10     12       7     29
19     20         Áustria     8     11       4     23
20     21          Suécia     8      7       6     21
21     22         Tunísia     8      7       3     18
22     23             Irã     7      3      13     23
23     24           Egito     6      9       8     23
24     25         Argélia     6      2       5     13
25     26   Nova Zelândia     6      1       3     10
26     27   Países Baixos     5     11      12     28
27     28         Nigéria     5      4       3     12
28     29       Dinamarca     5      3       7     15
29     30      Eslováquia     5      3       4     12
30     31          Itália     4      8       7     19
31     32          Israel     4      4       5     13
32     33       Finlândia     4      1       3      8
33     34          Grécia     3     13       4     20
34     35       Tailândia     3      6       6     15

**Quadro de medalhas dos Jogos Paralímpicos de Verão de 2008 - China**

In [19]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_2008 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_2008"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_2008, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_2008 = pd.read_html(io.StringIO(str(tabela_html)))[0]
df_para_2008 = df_para_2008.iloc[:, :6]
df_para_2008.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']
df_para_2008 = df_para_2008[df_para_2008['País'].str.contains('Total|TOTAL|País') == False].copy()

colunas_med = ['Ouro', 'Prata', 'Bronze', 'Total']
for col in colunas_med:
    df_para_2008[col] = pd.to_numeric(df_para_2008[col], errors='coerce').fillna(0).astype(int)

df_para_2008['Ordem'] = range(1, len(df_para_2008) + 1)
df_para_2008['País'] = df_para_2008['País'].str.strip()

pd.set_option('display.max_rows', None)

df_para_2008.to_csv("paralimpicos_pequim_2008.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_2008

    Ordem                        País  Ouro  Prata  Bronze  Total
0       1                   CHN China    89     70      52    211
1       2            GBR Grã-Bretanha    42     29      31    102
2       3          USA Estados Unidos    36     35      28     99
3       4                 UKR Ucrânia    24     18      32     74
4       5               AUS Austrália    23     29      27     79
5       6           RSA África do Sul    21      3       6     30
6       7                  CAN Canadá    19     20      21     60
7       8                  RUS Rússia    18     23      22     63
8       9                  BRA Brasil    16     14      17     47
9      10                 ESP Espanha    15     21      22     58
10     11                GER Alemanha    14     25      20     59
11     12                  FRA França    12     21      19     52
12     13           KOR Coreia do Sul    10      8      13     31
13     14                  MEX México    10      3       7     20
14     15                 TUN Tunísia     9      9       3     21
15     16         CZE República Checa     6      3      18     27
16     17                   JPN Japão     5     14       8     27
17     18                 POL Polônia     5     12      13     30
19     19                  GRE Grécia     5      9      10     24
20     20            BLR Bielorrússia     5      7       1     13
21     21                     IRI Irã     5      6       3     14
22     22                    CUB Cuba     5      3       6     14
23     23           NZL Nova Zelândia     5      3       4     12
24     24                  SWE Suécia     5      3       4     12
25     25               HKG Hong Kong     5      3       3     11
26     26                  KEN Quênia     5      3       1      9
27     27                  ITA Itália     4      7       7     18
28     28                   EGY Egito     4      4       4     12
29     29                 NGR Nigéria     4      4       1      9
30     30                 ALG Argélia     4      3       8     15
31     31                MAR Marrocos     4      1       2      7
32     32                 AUT Áustria     4      1       1      6
33     33                   SUI Suíça     3      2       6     11
34     34               DEN Dinamarca     3      2       4      9
35     35                 IRL Irlanda     3      1       1      5
36     36                 CRO Croácia     3      1       0      4
37     37              AZE Azerbaijão     2      3       5     10
38     38              SVK Eslováquia     2      3       1      6
39     39               FIN Finlândia     2      2       2      6
40     40               THA Tailândia     1      5       7     13
41     41                POR Portugal     1      4       2      7
42     42                 NOR Noruega     1      3       3      7
43     43                  CYP Chipre     1      2       1      4
44     44                 LAT Letônia     1      2       0      3
45     45               SIN Singapura     1      1       2      4
46     46               VEN Venezuela     1      1       2      4
47     47          KSA Arábia Saudita     1      1       0      2
48     48                 HUN Hungria     1      0       5      6
49     49            TPE Taipé Chinês     1      0       1      2
50     50                 TUR Turquia     1      0       1      2
51     51                MGL Mongólia     1      0       0      1
52     52                  ISR Israel     0      5       1      6
53     53                  ANG Angola     0      3       0      3
54     54                JOR Jordânia     0      2       2      4
55     55                LTU Lituânia     0      2       0      2
56     56                  SRB Sérvia     0      2       0      2
57     57               ARG Argentina     0      1       5      6
58     58               SLO Eslovênia     0      1       2      3
59     59                BUL Bulgária     0      1       1      2
60     60                COL Colômbia     0      1       1      2
61     61                  IRQ Iraque     0      1       1      2
62     62    BIH Bósnia e Herzegovina     0      1       0      1
63     63               PAK Paquistão     0      1       0      1
64     64        PNG Papua-Nova Guiné     0      1       0      1
65     65                 ROU Romênia     0      1       0      1
66     66  UAE Emirados Árabes Unidos     0      1       0      1
67     67                  LIB Líbano     0      0       2      2
68     68                 BEL Bélgica     0      0       1      1
69     69                 EST Estônia     0      0       1      1
70     70                 JAM Jamaica     0      0       1      1
71     71                    LAO Laos     0      0       1      1
72     72                 MAS Malásia     0      0       1      1
73     73                 NAM Namíbia     0      0       1      1
74     74              PUR Porto Rico     0      0       1      1
75     75                   SYR Síria     0      0       1      1

**Jogos Paralímpicos de Verão de 2012 - Grã Bretanha**

In [20]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_2012 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_2012"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_2012, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_2012 = pd.read_html(io.StringIO(str(tabela_html)))[0]
df_para_2012 = df_para_2012.iloc[:, :6]
df_para_2012.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_para_2012 = df_para_2012[df_para_2012['País'].str.contains('Total|TOTAL|País') == False].copy()

colunas_med = ['Ouro', 'Prata', 'Bronze', 'Total']
for col in colunas_med:
    df_para_2012[col] = pd.to_numeric(df_para_2012[col], errors='coerce').fillna(0).astype(int)

df_para_2012['Ordem'] = range(1, len(df_para_2012) + 1)
df_para_2012['País'] = df_para_2012['País'].str.strip()

pd.set_option('display.max_rows', None)

df_para_2012.to_csv("paralimpicos_londres_2012.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_2012

    Ordem                        País  Ouro  Prata  Bronze  Total
0       1                   CHN China    95     71      65    231
1       2                  RUS Rússia    36     39      27    102
2       3            GBR Grã-Bretanha    34     43      43    120
3       4                 UKR Ucrânia    32     24      28     84
4       5               AUS Austrália    32     22      30     84
5       6          USA Estados Unidos    31     29      37     97
6       7                  BRA Brasil    21     14       8     43
7       8                GER Alemanha    18     26      22     66
8       9                 POL Polônia    14     12       9     35
10     10                     IRI Irã    10      7       7     24
11     11           KOR Coreia do Sul     9      9       9     27
12     12                  ITA Itália     9      8      11     28
13     13                 TUN Tunísia     9      5       5     19
14     14                    CUB Cuba     9      5       3     17
15     15                  FRA França     8     19      18     45
16     16                 ESP Espanha     8     18      16     42
17     17           RSA África do Sul     8     12       9     29
18     18                 IRL Irlanda     8      3       5     16
19     19                  CAN Canadá     7     16       9     32
20     20           NZL Nova Zelândia     6      6       4     16
21     21                 NGR Nigéria     6      5       2     13
22     22                  MEX México     6      4      11     21
23     23                   JPN Japão     5      5       6     16
24     24            BLR Bielorrússia     5      2       4     11
25     25                 ALG Argélia     4      6       9     19
26     26              AZE Azerbaijão     4      5       3     12
27     27                   EGY Egito     4      4       7     15
28     28                  SWE Suécia     4      4       4     12
29     29                 AUT Áustria     4      3       6     13
30     30               THA Tailândia     4      2       2      8
31     31               FIN Finlândia     4      1       1      6
32     32                   SUI Suíça     3      6       4     13
33     33               HKG Hong Kong     3      3       6     12
34     34                 NOR Noruega     3      2       3      8
35     35                 BEL Bélgica     3      1       3      7
36     36                MAR Marrocos     3      0       3      6
37     37                 HUN Hungria     2      6       6     14
38     38                  SRB Sérvia     2      3       0      5
39     39                  KEN Quênia     2      2       2      6
40     40              SVK Eslováquia     2      1       3      6
41     41         CZE República Checa     1      6       4     11
42     42                 TUR Turquia     1      5       4     10
43     43                  GRE Grécia     1      3       8     12
44     44                  ISR Israel     1      2       5      8
45     45  UAE Emirados Árabes Unidos     1      1       1      3
46     46                 LAT Letônia     1      1       0      2
47     47                 NAM Namíbia     1      1       0      2
48     48                 ROU Romênia     1      1       0      2
49     49               DEN Dinamarca     1      0       4      5
50     50                  ANG Angola     1      0       1      2
51     51    BIH Bósnia e Herzegovina     1      0       0      1
52     52                   CHI Chile     1      0       0      1
53     53                    FIJ Fiji     1      0       0      1
54     54                ISL Islândia     1      0       0      1
55     55                 JAM Jamaica     1      0       0      1
56     56  MKD República da Macedônia     1      0       0      1
57     57                 CRO Croácia     0      2       3      5
58     58                BUL Bulgária     0      2       1      3
59     59                  IRQ Iraque     0      2       1      3
60     60                COL Colômbia     0      2       0      2
61     61               ARG Argentina     0      1       4      5
62     62                POR Portugal     0      1       2      3
63     63            TPE Taipé Chinês     0      1       2      3
64     64                 MAS Malásia     0      1       1      2
65     65               SIN Singapura     0      1       1      2
66     66          KSA Arábia Saudita     0      1       0      1
67     67                  CYP Chipre     0      1       0      1
68     68               SLO Eslovênia     0      1       0      1
69     69                 ETH Etiópia     0      1       0      1
70     70                   IND Índia     0      1       0      1
71     71             UZB Uzbequistão     0      1       0      1
72     72               VEN Venezuela     0      0       2      2
73     73               INA Indonésia     0      0       1      1
74     74               SRI Sri Lanka     0      0       1      1

In [25]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_2016 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_2016"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_2016, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_2016 = pd.read_html(io.StringIO(str(tabela_html)))[0]
df_para_2016.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total'] + list(df_para_2016.columns[6:])
df_para_2016 = df_para_2016[['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']]
df_para_2016 = df_para_2016[~df_para_2016['País'].str.contains('Total', case=False, na=False)].copy()

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
for col in colunas_num:
    df_para_2016[col] = pd.to_numeric(df_para_2016[col], errors='coerce').fillna(0).astype(int)

df_para_2016['Ordem'] = range(1, len(df_para_2016) + 1)
df_para_2016['País'] = df_para_2016['País'].str.strip()

pd.set_option('display.max_rows', None)

df_para_2016.to_csv("paralimpicos_rio_2016.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_2016

    Ordem                        País  Ouro  Prata  Bronze  Total
0       1                   CHN China   107     81      51    239
1       2            GBR Grã-Bretanha    64     39      44    147
2       3                 UKR Ucrânia    41     37      39    117
3       4          USA Estados Unidos    40     44      31    115
4       5               AUS Austrália    22     30      29     81
5       6                GER Alemanha    18     25      14     57
6       7           NED Países Baixos    17     19      26     62
7       8                  BRA Brasil    14     29      29     72
8       9                  ITA Itália    10     14      15     39
9      10                 POL Polônia     9     18      12     39
10     11                 ESP Espanha     9     14       8     31
11     12                  FRA França     9      5      14     28
12     13           NZL Nova Zelândia     9      5       7     21
13     14                  CAN Canadá     8     10      11     29
14     15                     IRI Irã     8      9       7     24
15     16             UZB Uzbequistão     8      6      17     31
16     17                 NGR Nigéria     8      2       2     12
17     18                    CUB Cuba     8      1       6     15
18     19            BLR Bielorrússia     8      0       2     10
19     20           KOR Coreia do Sul     7     11      17     35
20     21                 TUN Tunísia     7      6       6     19
21     22           RSA África do Sul     7      6       4     17
22     23               THA Tailândia     6      6       6     18
23     24                  GRE Grécia     5      4       4     13
24     25                 BEL Bélgica     5      3       3     11
25     26              SVK Eslováquia     5      3       3     11
26     27                 ALG Argélia     4      5       7     16
27     28                 IRL Irlanda     4      4       3     11
28     29                  MEX México     4      2       9     15
29     30                   EGY Egito     3      5       4     12
30     31                  SRB Sérvia     3      2       4      9
31     32                 NOR Noruega     3      2       3      8
32     33                MAR Marrocos     3      2       2      7
33     34                 TUR Turquia     3      1       5      9
34     35                  KEN Quênia     3      1       2      6
35     36                 MAS Malásia     3      0       1      4
36     37                COL Colômbia     2      5      10     17
37     38  UAE Emirados Árabes Unidos     2      4       1      7
38     39                  IRQ Iraque     2      3       0      5
39     40               HKG Hong Kong     2      2       2      6
40     41                 CRO Croácia     2      2       1      5
41     42                   SUI Suíça     2      2       1      5
42     43                   IND Índia     2      1       1      4
43     44                LTU Lituânia     2      1       0      3
44     45                 LAT Letônia     2      0       2      4
45     46               SIN Singapura     2      0       1      3
46     47                 HUN Hungria     1      8       9     18
47     48              AZE Azerbaijão     1      8       2     11
48     49                  SWE Suécia     1      4       5     10
49     50                 AUT Áustria     1      4       4      9
50     51               DEN Dinamarca     1      2       4      7
51     52         CZE República Checa     1      2       4      7
52     53                 NAM Namíbia     1      2       2      5
53     54               ARG Argentina     1      1       3      5
54     55                  VIE Vietnã     1      1       2      4
55     56               FIN Finlândia     1      1       1      3
56     57       TTO Trinidad e Tobago     1      1       1      3
57     58             KAZ Cazaquistão     1      1       0      2
58     59               SLO Eslovênia     1      1       0      2
59     60                   BRN Barém     1      0       0      1
60     61                BUL Bulgária     1      0       0      1
61     62                 GEO Geórgia     1      0       0      1
62     63                  KUW Kuwait     1      0       0      1
63     64                   JPN Japão     0     10      14     24
64     65               VEN Venezuela     0      3       3      6
65     66                JOR Jordânia     0      2       1      3
66     67                   QAT Catar     0      2       0      2
67     68            TPE Taipé Chinês     0      1       1      2
68     69    BIH Bósnia e Herzegovina     0      1       0      1
69     70         CIV Costa do Marfim     0      1       0      1
70     71                 ETH Etiópia     0      1       0      1
71     72                  UGA Uganda     0      1       0      1
72     73                POR Portugal     0      0       4      4
73     74                  ISR Israel     0      0       3      3
74     75                MGL Mongólia     0      0       2      2
75     76          KSA Arábia Saudita     0      0       1      1
76     77              CPV Cabo Verde     0      0       1      1
77     78               PHI Filipinas     0      0       1      1
78     79               INA Indonésia     0      0       1      1
79     80              MOZ Moçambique     0      0       1      1
80     81               PAK Paquistão     0      0       1      1
81     82                 ROU Romênia     0      0       1      1
82     83               SRI Sri Lanka     0      0       1      1

**Jogos Paralímpicos de Verão de 2020 - Japão**

In [26]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_2020 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_2020"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_2020, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_2020 = pd.read_html(io.StringIO(str(tabela_html)))[0]
df_para_2020.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total'] + list(df_para_2020.columns[6:])
df_para_2020 = df_para_2020[['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']]
df_para_2020 = df_para_2020[~df_para_2020['País'].str.contains('Total', case=False, na=False)].copy()

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
for col in colunas_num:
    df_para_2020[col] = pd.to_numeric(df_para_2020[col], errors='coerce').fillna(0).astype(int)

df_para_2020['Ordem'] = range(1, len(df_para_2020) + 1)
df_para_2020['País'] = df_para_2020['País'].str.strip()

pd.set_option('display.max_rows', None)

df_para_2020.to_csv("paralimpicos_toquio_2020.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_2020

    Ordem                          País  Ouro  Prata  Bronze  Total
0       1                     CHN China    96     60      51    207
1       2              GBR Grã-Bretanha    41     38      45    124
2       3            USA Estados Unidos    37     36      31    104
3       4  RPC Comitê Paralímpico Russo    36     33      49    118
4       5             NED Países Baixos    25     17      17     59
5       6                   UKR Ucrânia    24     47      27     98
6       7                    BRA Brasil    22     20      30     72
7       8                 AUS Austrália    21     29      30     80
8       9                    ITA Itália    14     29      26     69
9      10                AZE Azerbaijão    14      1       4     19
10     11                     JPN Japão    13     15      23     51
11     12                  GER Alemanha    13     12      18     43
12     13                       IRI Irã    12     11       1     24
13     14                    FRA França    11     15      28     54
14     15                   ESP Espanha     9     15      12     36
15     16               UZB Uzbequistão     8      5       6     19
16     17                   POL Polônia     7      6      12     25
17     18                   HUN Hungria     7      5       4     16
18     19                     SUI Suíça     7      4       3     14
19     20                    MEX México     7      2      13     22
20     21             NZL Nova Zelândia     6      3       3     12
21     22                    ISR Israel     6      2       1      9
22     23                    CAN Canadá     5     10       6     21
23     24                     IND Índia     5      8       6     19
24     25                 THA Tailândia     5      5       8     18
25     26                SVK Eslováquia     5      2       4     11
26     27              BLR Bielorrússia     5      1       1      7
27     28                   TUN Tunísia     4      5       2     11
28     29                   ALG Argélia     4      4       4     12
29     30                  MAR Marrocos     4      4       3     11
30     31                   BEL Bélgica     4      3       8     15
31     32                   IRL Irlanda     4      2       1      7
32     33                   NGR Nigéria     4      1       5     10
33     34             RSA África do Sul     4      1       2      7
34     35                      CUB Cuba     4      1       1      6
35     36                  JOR Jordânia     4      0       1      5
36     37                  COL Colômbia     3      7      14     24
37     38                 VEN Venezuela     3      2       2      7
38     39                   MAS Malásia     3      2       0      5
39     40                 DEN Dinamarca     3      1       1      5
40     41             KOR Coreia do Sul     2     10      12     24
41     42                   TUR Turquia     2      4       9     15
42     43                 INA Indonésia     2      3       4      9
43     44           CZE República Checa     2      3       3      8
44     45                     CHI Chile     2      3       1      6
45     46                    SRB Sérvia     2      3       1      6
46     47                   NOR Noruega     2      0       2      4
47     48                 SGP Singapura     2      0       0      2
48     49                   AUT Áustria     1      5       3      9
49     50                    SWE Suécia     1      5       2      8
50     51                    GRE Grécia     1      3       7     11
51     52               KAZ Cazaquistão     1      3       1      5
52     53                 FIN Finlândia     1      3       1      5
53     54    UAE Emirados Árabes Unidos     1      1       1      3
54     55                CRC Costa Rica     1      1       0      2
55     56                   ECU Equador     1      0       2      3
56     57                    CYP Chipre     1      0       1      2
57     58                 SRI Sri Lanka     1      0       1      2
58     59                   ETH Etiópia     1      0       0      1
59     60                  MGL Mongólia     1      0       0      1
60     61                 PAK Paquistão     1      0       0      1
61     62                      PER Peru     1      0       0      1
62     63                 ARG Argentina     0      5       4      9
63     64                     EGY Egito     0      5       2      7
64     65                   CRO Croácia     0      3       4      7
65     66                   LAT Letônia     0      3       2      5
66     67                   GEO Geórgia     0      3       0      3
67     68                 HKG Hong Kong     0      2       3      5
68     69                  BUL Bulgária     0      2       0      2
69     70                    IRQ Iraque     0      1       2      3
70     71                 SLO Eslovênia     0      1       1      2
71     72                    KUW Kuwait     0      1       1      2
72     73                   NAM Namíbia     0      1       1      2
73     74                   ROU Romênia     0      1       1      2
74     75                    VIE Vietnã     0      1       0      1
75     76                  LTU Lituânia     0      0       3      3
76     77                  POR Portugal     0      0       2      2
77     78            KSA Arábia Saudita     0      0       1      1
78     79      BIH Bósnia e Herzegovina     0      0       1      1
79     80                     QAT Catar     0      0       1      1
80     81               ESA El Salvador     0      0       1      1
81     82                MNE Montenegro     0      0       1      1
82     83                       OMA Omã     0      0       1      1
83     84                    KEN Quênia     0      0       1      1
84     85              TPE Taipé Chinês     0      0       1      1
85     86                    UGA Uganda     0      0       1      1

**Jogos Paralímpicos de Verão de 2024 - Fança**

In [28]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

url_para_2024 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_2024"
headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (luis.oliveira@academico.ufpb.edu.br)"}

response = requests.get(url_para_2024, headers=headers)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')
tabela_html = soup.find("table", {"class": "wikitable"})

df_para_2024 = pd.read_html(io.StringIO(str(tabela_html)))[0]
df_para_2024.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total'] + list(df_para_2024.columns[6:])
df_para_2024 = df_para_2024[['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']]
df_para_2024 = df_para_2024[~df_para_2024['País'].str.contains('Total', case=False, na=False)].copy()

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
for col in colunas_num:
    df_para_2024[col] = pd.to_numeric(df_para_2024[col], errors='coerce').fillna(0).astype(int)

df_para_2024['Ordem'] = range(1, len(df_para_2024) + 1)
df_para_2024['País'] = df_para_2024['País'].str.strip()

pd.set_option('display.max_rows', None)

df_para_2024.to_csv("paralimpicos_paris_2024.csv", index=False, sep=',', encoding='utf-8-sig')

df_para_2024

    Ordem                                País  Ouro  Prata  Bronze  Total
0       1                           CHN China    94     76      50    220
1       2                    GBR Grã-Bretanha    49     44      31    124
2       3                  USA Estados Unidos    36     42      27    105
3       4                   NED Países Baixos    27     17      12     56
4       5    NPA Atletas Paralímpicos Neutros    26     22      23     71
5       6                          BRA Brasil    25     26      38     89
6       7                          ITA Itália    24     15      32     71
7       8                         UKR Ucrânia    22     28      32     82
8       9                          FRA França    19     28      28     75
9      10                       AUS Austrália    18     17      28     63
10     11                           JPN Japão    14     10      17     41
11     12                        GER Alemanha    10     14      25     49
12     13                          CAN Canadá    10      9      10     29
13     14                     UZB Uzbequistão    10      9       7     26
14     15                             IRI Irã     8     10       7     25
15     16                           SUI Suíça     8      8       5     21
16     17                         POL Polônia     8      6       9     23
17     18                         ESP Espanha     7     11      22     40
18     19                           IND Índia     7      9      13     29
19     20                        COL Colômbia     7      7      14     28
20     21                         BEL Bélgica     7      4       3     14
21     22                       THA Tailândia     6     11      13     30
22     23                   KOR Coreia do Sul     6     10      14     30
23     24                         TUR Turquia     6     10      12     28
24     25                            CUB Cuba     6      3       1     10
25     26                         ALG Argélia     6      0       5     11
26     27                         HUN Hungria     5      6       4     15
27     28                         TUN Tunísia     5      3       3     11
28     29                      AZE Azerbaijão     4      2       5     11
29     30                          ISR Israel     4      2       4     10
30     31                          MEX México     3      6       8     17
31     32                        MAR Marrocos     3      6       6     15
32     33                       HKG Hong Kong     3      4       1      8
33     34                          GRE Grécia     3      3       7     13
34     35                       VEN Venezuela     3      2       1      6
35     36                      SVK Eslováquia     3      2       0      5
36     37                         LAT Letônia     3      1       0      4
37     38                       ARG Argentina     2      3       8     13
38     39                       DEN Dinamarca     2      3       5     10
39     40                     KAZ Cazaquistão     2      3       4      9
40     41                         NGR Nigéria     2      3       2      7
41     42                           EGY Egito     2      2       3      7
42     43                         MAS Malásia     2      2       1      5
43     44                        POR Portugal     2      1       4      7
44     45                         ETH Etiópia     2      1       0      3
45     46                       SIN Singapura     2      1       0      3
46     47                   RSA África do Sul     2      0       4      6
47     48                         ECU Equador     2      0       2      4
48     49                        JOR Jordânia     2      0       1      3
49     50                      CRC Costa Rica     2      0       0      2
50     51                       INA Indonésia     1      8       5     14
51     52                         GEO Geórgia     1      4       4      9
52     53                   NZL Nova Zelândia     1      4       4      9
53     54                         CZE Chéquia     1      4       3      8
54     55                         NOR Noruega     1      3       3      7
55     56                         IRL Irlanda     1      3       2      6
56     57                          SRB Sérvia     1      3       2      6
57     58                        MGL Mongólia     1      3       0      4
58     59                          IRQ Iraque     1      1       3      5
59     60                         CRO Croácia     1      1       2      4
60     61                           CHI Chile     1      0       4      5
61     62                          KUW Kuwait     1      0       1      2
62     63                         NAM Namíbia     1      0       1      2
63     64                         ROU Romênia     1      0       1      2
64     65                       SLO Eslovênia     1      0       1      2
65     66                        BUL Bulgária     1      0       0      1
66     67                  KSA Arábia Saudita     1      0       0      1
67     68                            PER Peru     1      0       0      1
68     69                    TPE Taipé Chinês     0      3       2      5
69     70                         AUT Áustria     0      3       1      4
70     71            BIH Bósnia e Herzegovina     0      2       0      2
71     72                       FIN Finlândia     0      1       3      4
72     73                          SWE Suécia     0      1       2      3
73     74                          CYP Chipre     0      1       1      2
74     75                        MDA Moldávia     0      1       1      2
75     76                          KEN Quênia     0      1       0      1
76     77                       SRI Sri Lanka     0      1       0      1
77     78               TTO Trinidad e Tobago     0      1       0      1
78     79  RPT Time Paralímpico de Refugiados     0      0       2      2
79     80                        LTU Lituânia     0      0       1      1
80     81                      LUX Luxemburgo     0      0       1      1
81     82                      MNE Montenegro     0      0       1      1
82     83                        MRI Maurício     0      0       1      1
83     84                           NEP Nepal     0      0       1      1
84     85                       PAK Paquistão     0      0       1      1
85     86                          VIE Vietnã     0      0       1      1