In [25]:
import pandas as pd

##### Tratamento do nome dos países para ficarem iguais em todos os datasets

*Olimpiadas*
Trata o texto do nome das olimpiadas pois estava diferente do que tem no pib, estava: USA Estados Unidos, após o tratamento fica uma coluna para o país que tem só o nome: Estados Unidos e outra coluna para a NOC que recebe a sigla (talvez use no futuro para comparar com a tabela de atletas em outras analises).

In [27]:
df_olimpiadas = pd.read_csv('medalhas_olimpiadas_wikipedia.csv', encoding='utf-8')
display(df_olimpiadas.head())

df_paraolimpiadas = pd.read_csv('medalhas_paralimpiadas_wikipedia.csv', encoding='utf-8')
display(df_paraolimpiadas.head())

   No.                 País  Jogos  Ouro  Prata  Bronze  Total
0    1   USA Estados Unidos     29  1101    880     781   2762
1    2  URS União Soviética      9   395    319     296   1010
2    3            CHN China     12   302    227     197    726
3    4     GBR Grã-Bretanha     30   300    338     344    982
4    5           FRA França     30   240    280     298    818

                           País   №  Ouro  Prata  Bronze  Total
0           África do Sul (RSA)  11   121     95      88    304
1            Alemanha (GER) [a]   8   199    266     253    718
2  Alemanha Ocidental (FRG) [b]   8   322    260     246    828
3   Alemanha Oriental (GDR) [c]   1     0      3       1      4
4                  Angola (ANG)   6     4      3       1      8

olimpiadas

In [28]:
df_olimpiadas_limpo = df_olimpiadas['País'].str.extract(r'^([A-Z]{3})\s+(.*)')
df_olimpiadas_limpo.columns = ['NOC', 'País_Limpo']

df_olimpiadas['NOC'] = df_olimpiadas_limpo['NOC']
df_olimpiadas['País'] = df_olimpiadas_limpo['País_Limpo']

df_olimpiadas['País'] = df_olimpiadas['País'].str.replace(r'\[.*\]|\*', '', regex=True).str.strip()

display(df_olimpiadas.head())

   No.             País  Jogos  Ouro  Prata  Bronze  Total  NOC
0    1   Estados Unidos     29  1101    880     781   2762  USA
1    2  União Soviética      9   395    319     296   1010  URS
2    3            China     12   302    227     197    726  CHN
3    4     Grã-Bretanha     30   300    338     344    982  GBR
4    5           França     30   240    280     298    818  FRA

In [29]:
df_olimpiadas.to_csv('olimpiadas_medalhas_arrumado.csv', index=False, encoding='utf-8')

*Trata para as paralimpiadas*

trata o nome do país para ficar igual aos do pib, estava com o nome do país e o código entre parênteses, agora só tem o nome do paíse o codigo do país em uma coluna separada, isso facilita a comparação entre os dataframes

paralimpiadas

In [31]:
df_paraolimpiadas['NOC'] = df_paraolimpiadas['País'].str.extract(r'\((.*?)\)')

df_paraolimpiadas['País'] = df_paraolimpiadas['País'].str.replace(r'\s*\(.*', '', regex=True)
df_paraolimpiadas['País'] = df_paraolimpiadas['País'].str.replace(r'\[.*\]', '', regex=True).str.strip()
display(df_paraolimpiadas.head())

                 País   №  Ouro  Prata  Bronze  Total  NOC
0       África do Sul  11   121     95      88    304  RSA
1            Alemanha   8   199    266     253    718  GER
2  Alemanha Ocidental   8   322    260     246    828  FRG
3   Alemanha Oriental   1     0      3       1      4  GDR
4              Angola   6     4      3       1      8  ANG

Junta as Tres alemanhas paralimpicas em uma só, soma as medalhas e usa o código GER.

In [32]:
alemanhas = ['Alemanha Ocidental', 'Alemanha Oriental']
df_paraolimpiadas['País'] = df_paraolimpiadas['País'].replace(alemanhas, 'Alemanha')

df_para_final = df_paraolimpiadas.groupby('País').agg({
    'Total': 'sum',
    'NOC': 'first' 
}).reset_index()
display(df_para_final.head())

             País  Total  NOC
0        Alemanha   1550  GER
1          Angola      8  ANG
2       Argentina    165  ARG
3         Argélia     85  ALG
4  Arábia Saudita      5  KSA

Exclui a linha que tinhas a soma de todas as medalhas

In [35]:
df_para_final = df_para_final[df_para_final['País'] != 'Totais']

display(df_para_final)

               País  Total  NOC
0          Alemanha   1550  GER
1            Angola      8  ANG
2         Argentina    165  ARG
3           Argélia     85  ALG
4    Arábia Saudita      5  KSA
..              ...    ...  ...
125          Vietnã      5  VIE
126        Zimbabwe     17  ZIM
127   África do Sul    304  RSA
128         Áustria    372  AUT
129           Índia     31  IND

[129 rows x 3 columns]

In [36]:
df_para_final.to_csv('paralimpiada_medalhas_arrumado.csv', index=False, encoding='utf-8')