**Jogos Paralímpicos de Verão de 1960 - Roma**

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import io

In [2]:
url_1960 = "https://www.paralympic.org/rome-1960/results/medalstandings"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_1960, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table")

df_1960 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1960 = df_1960.iloc[:, :7]
df_1960.columns = ['Ordem', 'País', 'CPN', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1960 = df_1960.fillna(0)
df_1960 = df_1960[df_1960['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ordem', 'Ouro', 'Prata', 'Bronze', 'Total']
df_1960[colunas_num] = df_1960[colunas_num].astype(int)

df_1960['País'] = df_1960['País'].str.strip()

df_1960

    Ordem                      País  CPN  Ouro  Prata  Bronze  Total
0       1                     Italy  ITA    29     28      23     80
1       2             Great Britain  GBR    20     15      20     55
2       3                   Germany  GER    15      6       9     30
3       4                   Austria  AUT    11      8      11     30
4       5  United States of America  USA    11      7       7     25
5       6                    Norway  NOR     9      3       4     16
6       7                 Australia  AUS     3      6       1     10
7       8               Netherlands  NED     3      6       0      9
8       9                    France  FRA     3      3       1      7
9      10                 Argentina  ARG     2      3       1      6
10     11                  Rhodesia  RHO     2      1       2      5
11     12                   Ireland  IRL     2      0       0      2
12     13               Switzerland  SUI     1      3       0      4
13     14                   Belgium  BEL     1      1       1      3
14     15                   Finland  FIN     1      0       0      1
15     16                    Israel  ISR     0      2       2      4
16     16                     Malta  MLT     0      2       2      4

In [3]:
df_1960.to_csv("medalhas_roma_1960_Para.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Paralímpicos de Verão de 1964 - Japão**

In [4]:
url_1964 = "https://www.paralympic.org/tokyo-1964/results/medalstandings"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_1964, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table")

df_1964 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1964 = df_1964.iloc[:, :7]
df_1964.columns = ['Ordem', 'País', 'CPN', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1964 = df_1964.fillna(0)
df_1964 = df_1964[df_1964['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ordem', 'Ouro', 'Prata', 'Bronze', 'Total']
df_1964[colunas_num] = df_1964[colunas_num].astype(int)

df_1964['País'] = df_1964['País'].str.strip()

df_1964

    Ordem                      País  CPN  Ouro  Prata  Bronze  Total
0       1  United States of America  USA    50     41      32    123
1       2             Great Britain  GBR    18     23      20     61
2       3                     Italy  ITA    14     15      16     45
3       4                 Australia  AUS    12     11       7     30
4       5                  Rhodesia  RHO    10      5       2     17
5       6              South Africa  RSA     8      8       3     19
6       7                    Israel  ISR     7      3      11     21
7       8                 Argentina  ARG     6     15      16     37
8       9                   Germany  GER     5      2       5     12
9      10               Netherlands  NED     4      6       4     14
10     11                    France  FRA     4      2       5     11
11     12                   Austria  AUT     4      1       7     12
12     13                     Japan  JPN     1      5       4     10
13     14                   Belgium  BEL     1      0       2      3
14     15               Switzerland  SUI     0      1       0      1
15     16                     Malta  MLT     0      0       2      2
16     17                    Sweden  SWE     0      0       1      1

In [5]:
df_1964.to_csv("medalhas_tokyo_1964_Para.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Paralímpicos de Verão de 1968 - Israel**

In [6]:
url_1968 = "https://www.paralympic.org/tel-aviv-1968/results/medalstandings"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_1968, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table")

df_1968 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1968 = df_1968.iloc[:, :7]
df_1968.columns = ['Ordem', 'País', 'CPN', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1968 = df_1968.fillna(0)
df_1968 = df_1968[df_1968['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ordem', 'Ouro', 'Prata', 'Bronze', 'Total']
df_1968[colunas_num] = df_1968[colunas_num].astype(int)

df_1968['País'] = df_1968['País'].str.strip()

df_1968

    Ordem                      País  CPN  Ouro  Prata  Bronze  Total
0       1  United States of America  USA    33     27      39     99
1       2             Great Britain  GBR    29     20      20     69
2       3                    Israel  ISR    18     21      23     62
3       4                 Australia  AUS    15     16       7     38
4       5                    France  FRA    13     10       9     32
5       6              West Germany  FRG    12     12      11     35
6       7                     Italy  ITA    12     10      17     39
7       8               Netherlands  NED    12      4       4     20
8       9                 Argentina  ARG    10     10      10     30
9      10              South Africa  RSA     9     10       7     26
10     11                  Rhodesia  RHO     6      7       7     20
11     12                    Canada  CAN     6      6       7     19
12     13                    Norway  NOR     5      3       1      9
13     14                   Jamaica  JAM     3      1       1      5
14     15                   Austria  AUT     2      7      10     19
15     16                     Japan  JPN     2      2       8     12
16     17                    Sweden  SWE     1      6       4     11
17     18               New Zealand  NZL     1      2       1      4
18     19                   Ireland  IRL     0      4       5      9
19     20                   Belgium  BEL     0      3       3      6
20     21                     Spain  ESP     0      3       1      4
21     22               Switzerland  SUI     0      2       6      8

In [7]:
df_1968.to_csv("medalhas_telaviv_1968_Para.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Paralímpicos de Verão de 1972 - Alemanha**

In [8]:
url_1972 = "https://www.paralympic.org/heidelberg-1972/results/medalstandings"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_1972, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table")

df_1972 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1972 = df_1972.iloc[:, :7]
df_1972.columns = ['Ordem', 'País', 'CPN', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1972 = df_1972.fillna(0)
df_1972 = df_1972[df_1972['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ordem', 'Ouro', 'Prata', 'Bronze', 'Total']
df_1972[colunas_num] = df_1972[colunas_num].astype(int)

df_1972['País'] = df_1972['País'].str.strip()

df_1972

    Ordem                      País  CPN  Ouro  Prata  Bronze  Total
0       1              West Germany  FRG    28     17      22     67
1       2  United States of America  USA    17     27      31     75
2       3             Great Britain  GBR    16     15      21     52
3       4              South Africa  RSA    16     12      13     41
4       5               Netherlands  NED    14     13      11     38
5       6                    Poland  POL    14     12       7     33
6       7                    France  FRA    10      8      15     33
7       8                    Israel  ISR     9     10       9     28
8       9                     Italy  ITA     8      4       5     17
9      10                   Jamaica  JAM     8      3       4     15
10     11                 Australia  AUS     6      9      10     25
11     12                   Austria  AUT     6      6       6     18
12     13                    Canada  CAN     5      6       8     19
13     14                    Sweden  SWE     5      6       6     17
14     15                     Japan  JPN     4      5       3     12
15     16         Republic of Korea  KOR     4      2       1      7
16     17                  Rhodesia  RHO     3      5       4     12
17     18               New Zealand  NZL     3      3       3      9
18     19               Switzerland  SUI     3      2       4      9
19     20                 Argentina  ARG     2      4       3      9
20     21                   Ireland  IRL     2      4       2      8
21     22                    Norway  NOR     1      5       4     10
22     23                   Belgium  BEL     1      1       2      4
23     23                Yugoslavia  YUG     1      1       2      4
24     24                     India  IND     1      0       0      1
25     24                     Kenya  KEN     1      0       0      1
26     25                     Spain  ESP     0      4       0      4
27     26                   Finland  FIN     0      2       1      3
28     27          Hong Kong, China  HKG     0      1       1      2
29     28            Czechoslovakia  TCH     0      0       1      1
30     28                   Hungary  HUN     0      0       1      1

In [9]:
df_1972.to_csv("medalhas_heidelberg_1972_Para.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Paralímpicos de Verão de 1976 - Canadá**

In [10]:
url_1976 = "https://www.paralympic.org/toronto-1976/results/medalstandings"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_1976, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table")

df_1976 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1976 = df_1976.iloc[:, :7]
df_1976.columns = ['Ordem', 'País', 'CPN', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1976 = df_1976.fillna(0)
df_1976 = df_1976[df_1976['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ordem', 'Ouro', 'Prata', 'Bronze', 'Total']
df_1976[colunas_num] = df_1976[colunas_num].astype(int)

df_1976['País'] = df_1976['País'].str.strip()

df_1976

    Ordem                      País  CPN  Ouro  Prata  Bronze  Total
0       1  United States of America  USA    66     44      45    155
1       2               Netherlands  NED    45     25      14     84
2       3                    Israel  ISR    40     13      16     69
3       4              West Germany  FRG    37     34      26     97
4       5             Great Britain  GBR    29     28      37     94
5       6                    Canada  CAN    25     26      26     77
6       7                    Poland  POL    24     17      12     53
7       8                    France  FRA    23     21      14     58
8       9                    Sweden  SWE    21     28      25     74
9      10                   Austria  AUT    18     16      17     51
10     11                 Australia  AUS    16     18       7     41
11     12                    Mexico  MEX    16     14       9     39
12     13                   Finland  FIN    12     20      18     50
13     14                     Japan  JPN    10      6       3     19
14     15               Switzerland  SUI     9     12      10     31
15     16                    Norway  NOR     9      6       4     19
16     17                   Belgium  BEL     7      7       8     22
17     18               New Zealand  NZL     7      1       5     13
18     19              South Africa  RSA     6      9      11     26
19     20                     Egypt  EGY     5      2       1      8
20     21                   Ireland  IRL     4     10       6     20
21     22                     Spain  ESP     4      6       2     12
22     23                 Argentina  ARG     3      4       7     14
23     24                   Denmark  DEN     3      0       3      6
24     25                     Italy  ITA     2      5      11     18
25     26                 Indonesia  INA     2      1       3      6
26     27         Republic of Korea  KOR     1      2       1      4
27     28                     Burma  BIR     1      1       1      3
28     29                      Peru  PER     1      0       2      3
29     30                   Hungary  HUN     1      0       1      2
30     31          Hong Kong, China  HKG     0      1       2      3
31     32                    Brazil  BRA     0      1       0      1
32     33                 Guatemala  GUA     0      0       1      1

In [11]:
df_1976.to_csv("medalhas_toronto_1976_Para.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Paralímpicos de Verão de 1980 - Países Baixos**

In [12]:
url_1980 = "https://www.paralympic.org/arnhem-1980/results/medalstandings"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_1980, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table")

df_1980 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1980 = df_1980.iloc[:, :7]
df_1980.columns = ['Ordem', 'País', 'CPN', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1980 = df_1980.fillna(0)
df_1980 = df_1980[df_1980['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ordem', 'Ouro', 'Prata', 'Bronze', 'Total']
df_1980[colunas_num] = df_1980[colunas_num].astype(int)

df_1980['País'] = df_1980['País'].str.strip()

df_1980

    Ordem                      País  CPN  Ouro  Prata  Bronze  Total
0       1  United States of America  USA    75     66      54    195
1       2                    Poland  POL    75     50      52    177
2       3              West Germany  FRG    68     48      46    162
3       4                    Canada  CAN    64     35      31    130
4       5             Great Britain  GBR    47     32      21    100
5       6               Netherlands  NED    33     31      36    100
6       7                    Sweden  SWE    31     36      24     91
7       8                    France  FRA    28     26      31     85
8       9                    Mexico  MEX    20     16       6     42
9      10                    Norway  NOR    15     13       8     36
10     11                   Austria  AUT    14     23       8     45
11     12                    Israel  ISR    13     18      15     46
12     13                   Belgium  BEL    13     12      17     42
13     14                 Australia  AUS    12     21      22     55
14     15               Switzerland  SUI     9     10      10     29
15     16                     Japan  JPN     9     10       7     26
16     17                   Finland  FIN     8     19      13     40
17     18                   Jamaica  JAM     7      7       5     19
18     19               New Zealand  NZL     7      6       6     19
19     20                     Italy  ITA     6      5       9     20
20     21                   Denmark  DEN     6      4       7     17
21     22                     Egypt  EGY     4      7       3     14
22     23                Yugoslavia  YUG     4      5       9     18
23     24                 Argentina  ARG     4      5       6     15
24     25                   Ireland  IRL     4      2      11     17
25     26         Republic of Korea  KOR     2      2       1      5
26     26                    Kuwait  KUW     2      2       1      5
27     27                 Indonesia  INA     2      0       4      6
28     28                     Spain  ESP     1     13       9     23
29     29                     Kenya  KEN     1      2       0      3
30     30                  Colombia  COL     1      0       1      2
31     30                   Iceland  ISL     1      0       1      2
32     31                     Sudan  SUD     1      0       0      1
33     32                  Zimbabwe  ZIM     0      8       4     12
34     33                   Bahamas  BAH     0      1       2      3
35     33          Hong Kong, China  HKG     0      1       2      3
36     34            Czechoslovakia  TCH     0      1       1      2
37     35                    Greece  GRE     0      0       1      1
38     35                Luxembourg  LUX     0      0       1      1
39     35                     Malta  MLT     0      0       1      1

In [13]:
df_1980.to_csv("medalhas_arnhem_1980_Para.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Paralímpicos de Verão de 1984 - Grã-Betanha/EUA**

In [14]:
url_1984 = "https://www.paralympic.org/stoke-mandeville-new-york-1984/results/medalstandings"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_1984, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table")

df_1984 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1984 = df_1984.iloc[:, :7]
df_1984.columns = ['Ordem', 'País', 'CPN', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1984 = df_1984.fillna(0)
df_1984 = df_1984[df_1984['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ordem', 'Ouro', 'Prata', 'Bronze', 'Total']
df_1984[colunas_num] = df_1984[colunas_num].astype(int)

df_1984['País'] = df_1984['País'].str.strip()

df_1984

    Ordem                        País  CPN  Ouro  Prata  Bronze  Total
0       1    United States of America  USA   137    131     129    397
1       2               Great Britain  GBR   107    112     112    331
2       3                      Canada  CAN    87     82      69    238
3       4                      Sweden  SWE    83     43      34    160
4       5                West Germany  FRG    81     76      75    232
5       6                      France  FRA    71     69      46    186
6       7                 Netherlands  NED    55     52      28    135
7       8                   Australia  AUS    49     54      51    154
8       9                      Poland  POL    46     39      21    106
9      10                      Norway  NOR    30     30      30     90
10     11                     Denmark  DEN    30     13      16     59
11     12                       Spain  ESP    22     10      12     44
12     13                     Belgium  BEL    21     23      14     58
13     14                     Ireland  IRL    20     15      31     66
14     15                     Finland  FIN    18     14      27     59
15     16                 Switzerland  SUI    18     13      12     43
16     17                     Austria  AUT    14     20      10     44
17     18                     Hungary  HUN    12     13       3     28
18     19                      Israel  ISR    11     21      12     44
19     20                  Yugoslavia  YUG    11     10      11     32
20     21                       Italy  ITA     9     19      14     42
21     22                       Japan  JPN     9      7       8     24
22     23                 New Zealand  NZL     8     10       7     25
23     24                      Brazil  BRA     7     17       4     28
24     25                      Mexico  MEX     6     14      17     37
25     26                    Portugal  POR     4      3       7     14
26     27            Hong Kong, China  HKG     3      5       9     17
27     28  People's Republic of China  CHN     2     12       8     22
28     29         Trinidad and Tobago  TTO     2      0       1      3
29     30                  Luxembourg  LUX     1      4       1      6
30     31                      Kuwait  KUW     1      3       4      8
31     32                       Burma  BIR     1      2       1      4
32     33                       Egypt  EGY     1      1       5      7
33     34                       Kenya  KEN     1      1       1      3
34     35                East Germany  GDR     0      3       1      4
35     36                     Iceland  ISL     0      2       8     10
36     37                       India  IND     0      2       2      4
37     37           Republic of Korea  KOR     0      2       2      4
38     38                      Jordan  JOR     0      1       2      3
39     38                    Zimbabwe  ZIM     0      1       2      3
40     39                     Bahamas  BAH     0      1       1      2
41     39                   Indonesia  INA     0      1       1      2
42     40                     Bahrain  BRN     0      0       2      2

In [15]:
df_1984.to_csv("medalhas_stoke_ny_1984_Para.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Paralímpicos de Verão de 1988 - Coreia do Sul**

In [16]:
url_1988 = "https://www.paralympic.org/seoul-1988/results/medalstandings"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_1988, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table")

df_1988 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1988 = df_1988.iloc[:, :7]
df_1988.columns = ['Ordem', 'País', 'CPN', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1988 = df_1988.fillna(0)
df_1988 = df_1988[df_1988['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ordem', 'Ouro', 'Prata', 'Bronze', 'Total']
df_1988[colunas_num] = df_1988[colunas_num].astype(int)

df_1988['País'] = df_1988['País'].str.strip()

df_1988

    Ordem                        País  CPN  Ouro  Prata  Bronze  Total
0       1    United States of America  USA    91     90      88    269
1       2                West Germany  FRG    76     65      52    193
2       3               Great Britain  GBR    65     65      54    184
3       4                      Canada  CAN    55     42      55    152
4       5                      France  FRA    46     44      50    140
5       6                      Sweden  SWE    42     38      23    103
6       7           Republic of Korea  KOR    40     35      19     94
7       8                 Netherlands  NED    30     24      29     83
8       9                   Australia  AUS    23     34      38     95
9      10                      Poland  POL    23     25      33     81
10     11                     Denmark  DEN    23     19      22     64
11     12                        USSR  URS    21     20      15     56
12     13                       Spain  ESP    18     13      12     43
13     14                       Japan  JPN    17     12      17     46
14     15  People's Republic of China  CHN    16     17       8     41
15     16                       Italy  ITA    16     15      27     58
16     17                     Belgium  BEL    15     18       8     41
17     18                      Israel  ISR    15     14      16     45
18     19                     Ireland  IRL    13     11      18     42
19     20                     Austria  AUT    13      7      15     35
20     21                 Switzerland  SUI    12     12      11     35
21     22                     Finland  FIN    11     23      16     50
22     23                      Norway  NOR    11     11      15     37
23     24                      Mexico  MEX     8      9       7     24
24     25                      Kuwait  KUW     5      5       7     17
25     26                      Brazil  BRA     4      9      14     27
26     27                  Yugoslavia  YUG     4      4      11     19
27     28    Islamic Republic of Iran  IRI     4      1       3      8
28     29                    Portugal  POR     3      5       6     14
29     30                 New Zealand  NZL     2      4      11     17
30     31                     Iceland  ISL     2      2       7     11
31     32                    Bulgaria  BUL     2      1       0      3
32     33                     Jamaica  JAM     1      4       3      8
33     34                       Egypt  EGY     1      3       3      7
34     34               Faroe Islands  FRO     1      3       3      7
35     35                 Puerto Rico  PUR     1      2       0      3
36     36                     Bahrain  BRN     1      1       1      3
37     37                   Guatemala  GUA     1      0       0      1
38     38                   Argentina  ARG     0      7       2      9
39     39                     Hungary  HUN     0      5       7     12
40     40                       Kenya  KEN     0      4       1      5
41     41            Hong Kong, China  HKG     0      2       7      9
42     42                   Indonesia  INA     0      2       0      2
43     43                      Greece  GRE     0      1       3      4
44     44              Czechoslovakia  TCH     0      1       0      1
45     44                    Thailand  THA     0      1       0      1
46     45                     Tunisia  TUN     0      0       2      2
47     46                    Malaysia  MAS     0      0       1      1
48     46                     Morocco  MAR     0      0       1      1

In [17]:
df_1988.to_csv("medalhas_seoul_1988_Para.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Paralímpicos de Verão de 1992 - Espanha**

In [18]:
url_1992 = "https://www.paralympic.org/barcelona-1992/results/medalstandings"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_1992, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table")

df_1992 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1992 = df_1992.iloc[:, :7]
df_1992.columns = ['Ordem', 'País', 'CPN', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1992 = df_1992.fillna(0)
df_1992 = df_1992[df_1992['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ordem', 'Ouro', 'Prata', 'Bronze', 'Total']
df_1992[colunas_num] = df_1992[colunas_num].astype(int)

df_1992['País'] = df_1992['País'].str.strip()

df_1992

,Ordem,País,CPN,Ouro,Prata,Bronze,Total
0,1,United States of America,USA,75,52,48,175
1,2,Germany,GER,61,51,59,171
2,3,Great Britain,GBR,40,47,41,128
3,4,France,FRA,36,36,34,106
4,5,Spain,ESP,34,31,42,107
5,6,Canada,CAN,28,21,26,75
6,7,Australia,AUS,24,27,25,76
7,8,Unified Team,EUN,16,14,15,45
8,9,Netherlands,NED,14,14,11,39
9,10,Norway,NOR,13,13,7,33
10,11,Denmark,DEN,12,22,12,46
11,12,Republic of Korea,KOR,11,15,18,44
12,13,People's Republic of China,CHN,11,7,7,25
13,14,Poland,POL,10,12,10,32
14,15,Italy,ITA,10,7,18,35
15,16,Japan,JPN,8,7,15,30
16,17,Finland,FIN,8,6,11,25
17,18,Sweden,SWE,7,22,9,38
18,19,Egypt,EGY,7,6,7,20
19,20,Switzerland,SUI,6,16,13,35
20,21,Belgium,BEL,5,5,7,17
21,22,Austria,AUT,5,4,13,22
22,23,New Zealand,NZL,5,1,0,6
23,24,Czechoslovakia,TCH,4,3,6,13
24,25,Hungary,HUN,4,3,4,11
25,26,Independent Paralympic Participants,IPP,4,3,1,8
26,27,South Africa,RSA,4,1,3,8
27,28,"Hong Kong, China",HKG,3,4,4,11
28,29,Cuba,CUB,3,3,3,9
29,29,Portugal,POR,3,3,3,9
30,30,Iceland,ISL,3,2,12,17
31,31,Brazil,BRA,3,0,4,7
32,32,Nigeria,NGR,3,0,0,3
33,33,Israel,ISR,2,4,5,11
34,34,Slovenia,SLO,2,0,1,3
35,35,Kuwait,KUW,1,3,1,5
36,36,Islamic Republic of Iran,IRI,1,2,1,4
37,37,Bulgaria,BUL,1,2,0,3
38,37,Panama,PAN,1,2,0,3
39,38,Argentina,ARG,1,1,0,2
40,39,Kenya,KEN,1,0,1,2
41,40,Lithuania,LTU,0,4,3,7
42,41,Ireland,IRL,0,3,4,7
43,42,Estonia,EST,0,2,1,3
44,42,Greece,GRE,0,2,1,3
45,43,Mexico,MEX,0,1,10,11
46,44,Jamaica,JAM,0,1,2,3
47,44,Malaysia,MAS,0,1,2,3
48,45,Faroe Islands,FRO,0,1,0,1
49,46,Bahrain,BRN,0,0,1,1
50,46,Chinese Taipei,TPE,0,0,1,1
51,46,Croatia,CRO,0,0,1,1
52,46,Iraq,IRQ,0,0,1,1
53,46,Thailand,THA,0,0,1,1
54,46,Venezuela,VEN,0,0,1,1

In [19]:
df_1992.to_csv("medalhas_barcelona_1992_Para.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Paralímpicos de Verão de 1996 - EUA**

In [20]:
url_1996 = "https://www.paralympic.org/atlanta-1996/results/medalstandings"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_1996, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table")

df_1996 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_1996 = df_1996.iloc[:, :7]
df_1996.columns = ['Ordem', 'País', 'CPN', 'Ouro', 'Prata', 'Bronze', 'Total']

df_1996 = df_1996.fillna(0)
df_1996 = df_1996[df_1996['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ordem', 'Ouro', 'Prata', 'Bronze', 'Total']
df_1996[colunas_num] = df_1996[colunas_num].astype(int)

df_1996['País'] = df_1996['País'].str.strip()

df_1996

    Ordem                        País  CPN  Ouro  Prata  Bronze  Total
0       1    United States of America  USA    46     46      65    157
1       2                   Australia  AUS    42     37      27    106
2       3                     Germany  GER    40     58      51    149
3       4               Great Britain  GBR    39     42      41    122
4       5                       Spain  ESP    39     31      36    106
5       6                      France  FRA    35     29      31     95
6       7                      Canada  CAN    24     21      24     69
7       8                 Netherlands  NED    17     11      17     45
8       9  People's Republic of China  CHN    16     13      10     39
9      10                       Japan  JPN    14     10      13     37
10     11                      Poland  POL    13     14       8     35
11     12           Republic of Korea  KOR    13      2      15     30
12     13                      Sweden  SWE    12     14      11     37
13     14                       Italy  ITA    11     20      14     45
14     15                South Africa  RSA    10      8      10     28
15     16          Russian Federation  RUS     9      7      11     27
16     17                      Norway  NOR     9      7       4     20
17     18                 Switzerland  SUI     9      6       6     21
18     19                 New Zealand  NZL     9      6       3     18
19     20    Islamic Republic of Iran  IRI     9      5       3     17
20     21                       Egypt  EGY     8     11      11     30
21     22                     Belgium  BEL     8     10       7     25
22     23                        Cuba  CUB     8      3       0     11
23     24                     Denmark  DEN     7     17      17     41
24     25                     Austria  AUT     6      6      10     22
25     26                    Portugal  POR     6      4       4     14
26     27            Hong Kong, China  HKG     5      5       5     15
27     28                     Iceland  ISL     5      4       5     14
28     29                     Hungary  HUN     5      2       3     10
29     30                     Finland  FIN     4      5       4     13
30     31                      Mexico  MEX     3      5       4     12
31     32                     Estonia  EST     3      4       2      9
32     33                     Belarus  BLR     3      3       7     13
33     34                   Lithuania  LTU     3      2       6     11
34     35                     Nigeria  NGR     3      2       3      8
35     36                     Czechia  CZE     2      7       1     10
36     37                      Brazil  BRA     2      6      13     21
37     38                   Argentina  ARG     2      5       2      9
38     39                    Slovakia  SVK     2      4       5     11
39     40                     Algeria  ALG     2      2       3      7
40     41                  Yugoslavia  YUG     2      2       0      4
41     42               Côte d'Ivoire  CIV     2      0       0      2
42     42                      Panama  PAN     2      0       0      2
43     43                     Ukraine  UKR     1      4       2      7
44     44                     Ireland  IRL     1      3       6     10
45     45                      Greece  GRE     1      1       3      5
46     46                      Kuwait  KUW     1      1       1      3
47     47                       Kenya  KEN     1      1       0      2
48     48              Chinese Taipei  TPE     1      0       2      3
49     49          Dominican Republic  DOM     1      0       0      1
50     49                        Peru  PER     1      0       0      1
51     50                      Israel  ISR     0      4       5      9
52     51                    Slovenia  SLO     0      2       3      5
53     52                     Tunisia  TUN     0      2       0      2
54     53                    Bulgaria  BUL     0      1       1      2
55     54                      Jordan  JOR     0      1       0      1
56     55         Republic of Moldova  MDA     0      0       2      2
57     55                    Thailand  THA     0      0       2      2
58     56                     Jamaica  JAM     0      0       1      1
59     56                     Uruguay  URU     0      0       1      1

In [21]:
df_1996.to_csv("medalhas_atlanta_1996_Para.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Paralímpicos de Verão de 2000 -  Austrália**

In [22]:
url_2000 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Paralímpicos_de_Verão_de_2000"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_2000, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table", {"class": "wikitable"})

df_2000 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_2000 = df_2000.iloc[:, :6]
df_2000.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_2000 = df_2000.fillna(0)
df_2000 = df_2000[df_2000['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_2000[colunas_num] = df_2000[colunas_num].astype(int)

df_2000['País'] = df_2000['País'].str.strip()

df_2000

   Ordem                País  Ouro  Prata  Bronze  Total
0      1       AUS Austrália    63     39      47    149
1      2    GBR Grã-Bretanha    41     43      47    131
2      3          CAN Canadá    38     33      25     96
3      4         ESP Espanha    38     29      38    105
4      5  USA Estados Unidos    36     39      34    109
..   ...                 ...   ...    ...     ...    ...
63    64           LBA Líbia     0      0       1      1
64    64       PLE Palestina     0      0       1      1
65    64       PHI Filipinas     0      0       1      1
66    64      PUR Porto Rico     0      0       1      1
67    64       VEN Venezuela     0      0       1      1

[68 rows x 6 columns]

In [23]:
df_2000.to_csv("medalhas_sydney_2000_Para.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Paralímpicos de Verão de 2004 - Grécia**

In [24]:
url_2004 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Paralímpicos_de_Verão_de_2004"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_2004, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table", {"class": "wikitable"})

df_2004 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_2004 = df_2004.iloc[:, :6]
df_2004.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_2004 = df_2004.fillna(0)
df_2004 = df_2004[df_2004['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_2004[colunas_num] = df_2004[colunas_num].astype(int)

df_2004['País'] = df_2004['País'].str.strip()

df_2004

    Ordem            País  Ouro  Prata  Bronze  Total
0       1           China    63     46      32    141
1       2    Grã-Bretanha    35     30      29     94
2       3          Canadá    28     19      25     72
3       4  Estados Unidos    27     22      39     88
4       5       Austrália    26     38      36    100
5       6         Ucrânia    24     12      19     55
6       7         Espanha    20     27      24     71
7       8        Alemanha    19     28      32     79
8       9          França    18     26      30     74
9      10           Japão    17     15      20     52
10     11          Rússia    16      8      17     41
11     12         Chéquia    16      8       7     31
12     13   África do Sul    15     13       7     35
13     14          Brasil    14     12       7     33
14     15          México    14     10      10     34
15     16   Coreia do Sul    11     11       6     28
16     17       Hong Kong    11      7       1     19
17     18         Polônia    10     25      19     54
18     19    Bielorrússia    10     12       7     29
19     20         Áustria     8     11       4     23
20     21          Suécia     8      7       6     21
21     22         Tunísia     8      7       3     18
22     23             Irã     7      3      13     23
23     24           Egito     6      9       8     23
24     25         Argélia     6      2       5     13
25     26   Nova Zelândia     6      1       3     10
26     27   Países Baixos     5     11      12     28
27     28         Nigéria     5      4       3     12
28     29       Dinamarca     5      3       7     15
29     30      Eslováquia     5      3       4     12
30     31          Itália     4      8       7     19
31     32          Israel     4      4       5     13
32     33       Finlândia     4      1       3      8
33     34          Grécia     3     13       4     20
34     35       Tailândia     3      6       6     15

In [25]:
df_2004.to_csv("medalhas_athens_2004_Para.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Paralímpicos de Verão de 2008 - China**

In [26]:
url_2008 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Paralímpicos_de_Verão_de_2008"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_2008, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table", {"class": "wikitable"})

df_2008 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_2008 = df_2008.iloc[:, :6]
df_2008.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_2008 = df_2008.fillna(0)
df_2008 = df_2008[df_2008['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_2008[colunas_num] = df_2008[colunas_num].astype(int)

df_2008['País'] = df_2008['País'].str.strip()

df_2008

    Ordem                País  Ouro  Prata  Bronze  Total
0     1.0           CHN China    89     70      52    211
1     2.0    GBR Grã-Bretanha    42     29      31    102
2     3.0  USA Estados Unidos    36     35      28     99
3     4.0         UKR Ucrânia    24     18      32     74
4     5.0       AUS Austrália    23     29      27     79
..    ...                 ...   ...    ...     ...    ...
71    0.0            LAO Laos     0      0       1      1
72    0.0         MAS Malásia     0      0       1      1
73    0.0         NAM Namíbia     0      0       1      1
74    0.0      PUR Porto Rico     0      0       1      1
75    0.0           SYR Síria     0      0       1      1

[76 rows x 6 columns]

In [27]:
df_2008.to_csv("medalhas_beijing_2008_Para.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Paralímpicos de Verão de 2012 - Grã-Betanha**

In [28]:
url_2012 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Paralímpicos_de_Verão_de_2012"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_2012, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table", {"class": "wikitable"})

df_2012 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_2012 = df_2012.iloc[:, :6]
df_2012.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_2012 = df_2012.fillna(0)
df_2012 = df_2012[df_2012['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_2012[colunas_num] = df_2012[colunas_num].astype(int)

df_2012['País'] = df_2012['País'].str.strip()

df_2012

    Ordem              País  Ouro  Prata  Bronze  Total
0     1.0         CHN China    95     71      65    231
1     2.0        RUS Rússia    36     39      27    102
2     3.0  GBR Grã-Bretanha    34     43      43    120
3     5.0       UKR Ucrânia    32     24      28     84
4     4.0     AUS Austrália    32     22      30     84
..    ...               ...   ...    ...     ...    ...
70    0.0         IND Índia     0      1       0      1
71    0.0   UZB Uzbequistão     0      1       0      1
72   73.0     VEN Venezuela     0      0       2      2
73   74.0     INA Indonésia     0      0       1      1
74    0.0     SRI Sri Lanka     0      0       1      1

[75 rows x 6 columns]

In [29]:
df_2012.to_csv("medalhas_london_2012_Para.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Paralímpicos de Verão de 2016 - Brasil**

In [30]:
url_2016 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Paralímpicos_de_Verão_de_2016"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_2016, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table", {"class": "wikitable"})

df_2016 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_2016 = df_2016.iloc[:, :6]
df_2016.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_2016 = df_2016.fillna(0)
df_2016 = df_2016[df_2016['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_2016[colunas_num] = df_2016[colunas_num].astype(int)

df_2016['País'] = df_2016['País'].str.strip()

df_2016

   Ordem                País  Ouro  Prata  Bronze  Total
0      1           CHN China   107     81      51    239
1      2    GBR Grã-Bretanha    64     39      44    147
2      3         UKR Ucrânia    41     37      39    117
3      4  USA Estados Unidos    40     44      31    115
4      5       AUS Austrália    22     30      29     81
..   ...                 ...   ...    ...     ...    ...
78     0       INA Indonésia     0      0       1      1
79     0      MOZ Moçambique     0      0       1      1
80     0       PAK Paquistão     0      0       1      1
81     0         ROU Romênia     0      0       1      1
82     0       SRI Sri Lanka     0      0       1      1

[83 rows x 6 columns]

In [31]:
df_2016.to_csv("medalhas_rio_2016_Para.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Paralímpicos de Verão de 2020 - Japão**

In [32]:
url_2020 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Paralímpicos_de_Verão_de_2020"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_2020, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table", {"class": "wikitable"})

df_2020 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_2020 = df_2020.iloc[:, :6]
df_2020.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_2020 = df_2020.fillna(0)
df_2020 = df_2020[df_2020['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_2020[colunas_num] = df_2020[colunas_num].astype(int)

df_2020['País'] = df_2020['País'].str.strip()

df_2020

   Ordem                          País  Ouro  Prata  Bronze  Total
0      1                     CHN China    96     60      51    207
1      2              GBR Grã-Bretanha    41     38      45    124
2      3            USA Estados Unidos    37     36      31    104
3      4  RPC Comitê Paralímpico Russo    36     33      49    118
4      5             NED Países Baixos    25     17      17     59
..   ...                           ...   ...    ...     ...    ...
81     0                MNE Montenegro     0      0       1      1
82     0                       OMA Omã     0      0       1      1
83     0                    KEN Quênia     0      0       1      1
84     0              TPE Taipé Chinês     0      0       1      1
85     0                    UGA Uganda     0      0       1      1

[86 rows x 6 columns]

In [33]:
df_2020.to_csv("medalhas_tokyo_2020_Para.csv", index=False, sep=',', encoding='utf-8-sig')

**Jogos Paralímpicos de Verão de 2024 - França**

In [34]:
url_2024 = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Paralímpicos_de_Verão_de_2024"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(url_2024, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find("table", {"class": "wikitable"})

df_2024 = pd.read_html(io.StringIO(str(tabela_html)))[0]

df_2024 = df_2024.iloc[:, :6]
df_2024.columns = ['Ordem', 'País', 'Ouro', 'Prata', 'Bronze', 'Total']

df_2024 = df_2024.fillna(0)
df_2024 = df_2024[df_2024['País'].str.contains('Total|TOTAL') == False]

colunas_num = ['Ouro', 'Prata', 'Bronze', 'Total']
df_2024[colunas_num] = df_2024[colunas_num].astype(int)

df_2024['País'] = df_2024['País'].str.strip()

df_2024

   Ordem                              País  Ouro  Prata  Bronze  Total
0      1                         CHN China    94     76      50    220
1      2                  GBR Grã-Bretanha    49     44      31    124
2      3                USA Estados Unidos    36     42      27    105
3      4                 NED Países Baixos    27     17      12     56
4      –  NPA Atletas Paralímpicos Neutros    26     22      23     71
..   ...                               ...   ...    ...     ...    ...
81    79                    MNE Montenegro     0      0       1      1
82    79                      MRI Maurício     0      0       1      1
83    79                         NEP Nepal     0      0       1      1
84    79                     PAK Paquistão     0      0       1      1
85    79                        VIE Vietnã     0      0       1      1

[86 rows x 6 columns]

In [35]:
df_2024.to_csv("medalhas_paris_2024_Para.csv", index=False, sep=',', encoding='utf-8-sig')