In [20]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
from io import StringIO

In [5]:
wiki_url = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos"
h2_id = "mwDSg"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (mariaeloisasilva498@gmail.com)"}

response = requests.get(wiki_url, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

sem_medalhas = soup.find('table', attrs={'id': h2_id})
df = pd.read_html(StringIO(str(sem_medalhas)))[0]

In [18]:
df_list = pd.read_html(StringIO(str(sem_medalhas)))
df = df_list[0]


df_limpo = df.iloc[:, :2] 

print(df_limpo.columns.tolist())
display(df_limpo.head())
df = df_limpo

df.rename(columns={'Unnamed: 1': 'Número de participações'}, inplace=True)
df

['País', 'Unnamed: 1']

                    País  Unnamed: 1
0    ASA Samoa Americana          10
1            AND Andorra          13
2             ANG Angola          11
3  ANT Antígua e Barbuda          12
4              ARU Aruba          10

                      País  Número de participações
0      ASA Samoa Americana                       10
1              AND Andorra                       13
2               ANG Angola                       11
3    ANT Antígua e Barbuda                       12
4                ARU Aruba                       10
..                     ...                      ...
67     NBO Bornéu do Norte                        1
68  ROC República da China                        3
69               SAA Sarre                        1
70      YAR Iêmen do Norte                        2
71        YMD Iêmen do Sul                        1

[72 rows x 2 columns]

In [19]:
df.to_csv("paises_olimpicos_sem_medalhas_wikipedia.csv", index= False, sep= ',', encoding= 'utf-8-sig')

Paises paralimpicos

In [21]:
wiki_url = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Paralímpicos"
table_id = "mwCgk"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (mariaeloisasilva498@gmail.com)"}

response = requests.get(wiki_url, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find(id= table_id)

html_string = str(tabela_html)
html_corrigido = html_string.replace('"5;"', '"5"')

In [27]:
df_list_no_paralympics = pd.read_html(StringIO(html_corrigido))
df_no_paralympics = df_list_no_paralympics[0]


df_no_paralympics.columns = df_no_paralympics.columns.get_level_values(-1)

df_limpo = df_no_paralympics.iloc[:, :2] 

print(df_limpo.columns.tolist())
display(df_limpo.head())

df_limpo.columns = ['Time (Código IPC)', 'Número de participações']

df_no_paralympics = df_limpo

df_no_paralympics

['Time (Código IPC)', '№ verão']

         Time (Código IPC)  № verão
0        Afeganistão (AFG)        5
1            Albânia (ALB)        1
2            Andorra (AND)        1
3  Antígua e Barbuda (ANT)        1
4            Armênia (ARM)        6

          Time (Código IPC)  Número de participações
0         Afeganistão (AFG)                        5
1             Albânia (ALB)                        1
2             Andorra (AND)                        1
3   Antígua e Barbuda (ANT)                        1
4             Armênia (ARM)                        6
..                      ...                      ...
65              Tonga (TGA)                        5
66      Turcomenistão (TKM)                        5
67            Vanuatu (VAN)                        3
68             Zâmbia (ZAM)                        4
69                   Totais                       16

[70 rows x 2 columns]

In [28]:
df.to_csv("paises_paralympicos_sem_medalhas_wikipedia.csv", index= False, sep= ',', encoding= 'utf-8-sig')